var internetExplorer=document.selection&&window.ActiveXObject&&/MSIE/.test(navigator.userAgent),webkit=/AppleWebKit/.test(navigator.userAgent),safari=/Apple Computer, Inc/.test(navigator.vendor),gecko=navigator.userAgent.match(/gecko\/(\d{8})/i);gecko&&(gecko=Number(gecko[1]));var mac=/Mac/.test(navigator.platform),brokenOpera=window.opera&&/Version\/10.[56]/.test(navigator.userAgent),slowWebkit=/AppleWebKit\/533/.test(navigator.userAgent);
function makeWhiteSpace(i){for(var k=[],l=!0;0<i;i--)k.push(l||1==i?nbsp:" "),l^=1;return k.join("")}function fixSpaces(i){" "==i.charAt(0)&&(i=nbsp+i.slice(1));return i.replace(/\t/g,function(){return makeWhiteSpace(indentUnit)}).replace(/[ \u00a0]{2,}/g,function(i){return makeWhiteSpace(i.length)})}function cleanText(i){return i.replace(/\u00a0/g," ").replace(/\u200b/g,"")}
function makePartSpan(i){var k=i;3==i.nodeType?k=i.nodeValue:i=document.createTextNode(k);var l=document.createElement("span");l.isPart=!0;l.appendChild(i);l.currentText=k;return l}function alwaysZero(){return 0}var webkitLastLineHack=webkit?function(i){var k=i.lastChild;if(!k||!k.hackBR)k=document.createElement("br"),k.hackBR=!0,i.appendChild(k)}:function(){};
function asEditorLines(i){var k=makeWhiteSpace(indentUnit);return map(i.replace(/\t/g,k).replace(/\u00a0/g," ").replace(/\r\n?/g,"\n").split("\n"),fixSpaces)}
var Editor=function(){function i(a,b){function c(a,g){if(3==a.nodeType){if((a.nodeValue=fixSpaces(a.nodeValue.replace(/[\r\u200b]/g,"").replace(/\n/g," "))).length)f=!1;d.push(a)}else if(isBR(a)&&0==a.childNodes.length)f=!0,d.push(a);else{for(var h=a.firstChild;h;h=h.nextSibling)c(h);!f&&t.hasOwnProperty(a.nodeName.toUpperCase())&&(f=!0,(!b||!g)&&d.push(document.createElement("br")))}}var d=[],f=!0;c(a,!0);return d}function k(a){function b(a){var b=a.parentNode,c=a.nextSibling;return function(a){b.insertBefore(a,
c)}}var c=[],d=null,f=!0;return{next:function(){if(!a)throw StopIteration;var e=a;a=e.nextSibling;var g;e.isPart&&1==e.childNodes.length&&3==e.firstChild.nodeType?(g=e.firstChild.nodeValue,e.dirty=e.dirty||g!=e.currentText,e.currentText=g,g=!/[\n\t\r]/.test(e.currentText)):g=!1;if(g)return c.push(e),f=!1,e.currentText;if(isBR(e))return f&&window.opera&&e.parentNode.insertBefore(makePartSpan(""),e),c.push(e),f=!0,"\n";g=!e.nextSibling;d=b(e);removeElement(e);e=i(e,g);for(g=0;g<e.length;g++){var h=
e,u=g,j=e[g],s="\n";3==j.nodeType?(select.snapshotChanged(),j=makePartSpan(j),s=j.currentText,f=!1):(f&&window.opera&&d(makePartSpan("")),f=!0);j.dirty=!0;c.push(j);d(j);h[u]=s}return e.join("")},nodes:c}}function l(a){for(;a&&!isBR(a);)a=a.previousSibling;return a}function p(a,b){a?isBR(a)&&(a=a.nextSibling):a=b.firstChild;for(;a&&!isBR(a);)a=a.nextSibling;return a}function q(a,b,c,d){function f(b){b=cleanText(a.history.textAfter(b));return d?b.toLowerCase():b}this.editor=a;this.history=a.history;
this.history.commit();this.valid=!!b;this.atOccurrence=!1;void 0==d&&(d="string"==typeof b&&b==b.toLowerCase());var e={node:null,offset:0},g=this;c&&"object"==typeof c&&"number"==typeof c.character?(a.checkLine(c.line),c={node:c.line,offset:c.character},this.pos={from:c,to:c}):this.pos=c?{from:select.cursorPos(a.container,!0)||e,to:select.cursorPos(a.container,!1)||e}:{from:e,to:e};if("string"!=typeof b)this.matches=function(a,c,d){if(a)for(var a=f(c).slice(0,d),e=a.match(b),d=0;e;){var h=a.indexOf(e[0]),
d=d+h,a=a.slice(h+1);if(h=a.match(b))e=h;else break}else{a=f(c).slice(d);d=(e=a.match(b))&&d+a.indexOf(e[0])}if(e){g.currentMatch=e;return{from:{node:c,offset:d},to:{node:c,offset:d+e[0].length}}}};else{d&&(b=b.toLowerCase());var h=b.split("\n");this.matches=1==h.length?function(a,c,d){var e=f(c),g=b.length,h;if(a?d>=g&&(h=e.lastIndexOf(b,d-g))!=-1:(h=e.indexOf(b,d))!=-1)return{from:{node:c,offset:h},to:{node:c,offset:h+g}}}:function(a,b,c){var d=a?h.length-1:0,e=h[d],g=f(b),i=a?g.indexOf(e)+e.length:
g.lastIndexOf(e);if(!(a?i>=c||i!=e.length:i<=c||i!=g.length-e.length))for(c=b;;){if(a&&!c)break;c=a?this.history.nodeBefore(c):this.history.nodeAfter(c);if(!a&&!c)break;g=f(c);e=h[a?--d:++d];if(d>0&&d<h.length-1)if(g!=e)break;else continue;d=a?g.lastIndexOf(e):g.indexOf(e)+e.length;if(a?d!=g.length-e.length:d!=e.length)break;return{from:{node:a?c:b,offset:a?d:i},to:{node:a?b:c,offset:a?i:d}}}}}}function o(a){this.options=a;window.indentUnit=a.indentUnit;var b=this.container=document.body;this.history=
new UndoHistory(b,a.undoDepth,a.undoDelay,this);var c=this;if(!o.Parser)throw"No parser loaded.";a.parserConfig&&o.Parser.configure&&o.Parser.configure(a.parserConfig);!a.readOnly&&!internetExplorer&&select.setCursorPos(b,{node:null,offset:0});this.dirty=[];this.importCode(a.content||"");this.history.onChange=a.onChange;if(a.readOnly)a.textWrapping||(b.style.whiteSpace="nowrap");else{!1!==a.continuousScanning&&(this.scanner=this.documentScanner(a.passTime),this.delayScanning());var d=function(){document.body.contentEditable!=
void 0&&internetExplorer?document.body.contentEditable="true":document.designMode="on";if(internetExplorer&&a.height!="dynamic")document.body.style.minHeight=window.frameElement.clientHeight-2*document.body.offsetTop-5+"px";document.documentElement.style.borderWidth="0";if(!a.textWrapping)b.style.whiteSpace="nowrap"};try{d()}catch(f){var e=addEventHandler(document,"focus",function(){e();d()},!0)}addEventHandler(document,"keydown",method(this,"keyDown"));addEventHandler(document,"keypress",method(this,
"keyPress"));addEventHandler(document,"keyup",method(this,"keyUp"));var g=function(){c.cursorActivity(false)};addEventHandler(internetExplorer?document.body:window,"mouseup",g);addEventHandler(document.body,"cut",g);gecko&&addEventHandler(window,"pagehide",function(){c.unloaded=true});addEventHandler(document.body,"paste",function(a){g();var b=null;try{var d=a.clipboardData||window.clipboardData;d&&(b=d.getData("Text"))}catch(e){}if(b!==null){a.stop();c.replaceSelection(b);select.scrollToCursor(c.container)}});
this.options.autoMatchParens&&addEventHandler(document.body,"click",method(this,"scheduleParenHighlight"))}}var t={P:!0,DIV:!0,LI:!0};q.prototype={findNext:function(){return this.find(!1)},findPrevious:function(){return this.find(!0)},find:function(a){function b(){var a={node:f,offset:e};c.pos={from:a,to:a};return c.atOccurrence=!1}if(!this.valid)return!1;var c=this,d=a?this.pos.from:this.pos.to,f=d.node,e=d.offset;f&&!f.parentNode&&(f=null,e=0);for(;;){if(this.pos=this.matches(a,f,e))return this.atOccurrence=
!0;if(a){if(!f)return b();f=this.history.nodeBefore(f);e=this.history.textAfter(f).length}else{d=this.history.nodeAfter(f);if(!d)return e=this.history.textAfter(f).length,b();f=d;e=0}}},select:function(){this.atOccurrence&&(select.setCursorPos(this.editor.container,this.pos.from,this.pos.to),select.scrollToCursor(this.editor.container))},replace:function(a){if(this.atOccurrence){var b=this.currentMatch;b&&(a=a.replace(/\\(\d)/,function(a,d){return b[d]}));this.pos.to=this.editor.replaceRange(this.pos.from,
this.pos.to,a);this.atOccurrence=!1}},position:function(){if(this.atOccurrence)return{line:this.pos.from.node,character:this.pos.from.offset}}};o.prototype={importCode:function(a){var b=asEditorLines(a);if(!this.options.incrementalLoading||1E3>b.length)this.history.push(null,null,b),this.history.reset();else{var c=0,d=this,f=function(){var a=b.slice(c,c+1E3);a.push("");d.history.push(d.history.nodeBefore(null),null,a);d.history.reset();c+=1E3;c<b.length&&parent.setTimeout(f,1E3)};f()}},getCode:function(){if(!this.container.firstChild)return"";
var a=[];select.markSelection();forEach(k(this.container.firstChild),method(a,"push"));select.selectMarked();webkit&&this.container.lastChild.hackBR&&a.pop();webkitLastLineHack(this.container);return cleanText(a.join(""))},checkLine:function(a){if(!1===a||!(null==a||a.parentNode==this.container||a.hackBR))throw parent.CodeMirror.InvalidLineHandle;},cursorPosition:function(a){null==a&&(a=!0);return(a=select.cursorPos(this.container,a))?{line:a.node,character:a.offset}:{line:null,character:0}},firstLine:function(){return null},
lastLine:function(){var a=this.container.lastChild;a&&(a=l(a));a&&a.hackBR&&(a=l(a.previousSibling));return a},nextLine:function(a){this.checkLine(a);a=p(a,this.container);return!a||a.hackBR?!1:a},prevLine:function(a){this.checkLine(a);return null==a?!1:l(a.previousSibling)},visibleLineCount:function(){for(var a=this.container.firstChild;a&&isBR(a);)a=a.nextSibling;return!a?!1:Math.floor((window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight)/a.offsetHeight)},selectLines:function(a,
b,c,d){this.checkLine(a);a={node:a,offset:b};b=null;void 0!==d&&(this.checkLine(c),b={node:c,offset:d});select.setCursorPos(this.container,a,b);select.scrollToCursor(this.container)},lineContent:function(a){for(var b=[],a=a?a.nextSibling:this.container.firstChild;a&&!isBR(a);a=a.nextSibling)b.push(nodeText(a));return cleanText(b.join(""))},setLineContent:function(a,b){this.history.commit();this.replaceRange({node:a,offset:0},{node:a,offset:this.history.textAfter(a).length},b);this.addDirtyNode(a);
this.scheduleHighlight()},removeLine:function(a){for(var b=a?a.nextSibling:this.container.firstChild;b;){var c=b.nextSibling;removeElement(b);if(isBR(b))break;b=c}this.addDirtyNode(a);this.scheduleHighlight()},insertIntoLine:function(a,b,c){var d=null;if("end"==b)d=p(a,this.container);else for(var f=a?a.nextSibling:this.container.firstChild;f;f=f.nextSibling){if(0==b){d=f;break}var e=nodeText(f);if(e.length>b){d=f.nextSibling;c=e.slice(0,b)+c+e.slice(b);removeElement(f);break}b-=e.length}b=asEditorLines(c);
for(c=0;c<b.length;c++)0<c&&this.container.insertBefore(document.createElement("BR"),d),this.container.insertBefore(makePartSpan(b[c]),d);this.addDirtyNode(a);this.scheduleHighlight()},selectedText:function(){var a=this.history;a.commit();var b=select.cursorPos(this.container,!0),c=select.cursorPos(this.container,!1);if(!b||!c)return"";if(b.node==c.node)return a.textAfter(b.node).slice(b.offset,c.offset);for(var d=[a.textAfter(b.node).slice(b.offset)],b=a.nodeAfter(b.node);b!=c.node;b=a.nodeAfter(b))d.push(a.textAfter(b));
d.push(a.textAfter(c.node).slice(0,c.offset));return cleanText(d.join("\n"))},replaceSelection:function(a){this.history.commit();var b=select.cursorPos(this.container,!0),c=select.cursorPos(this.container,!1);b&&c&&(c=this.replaceRange(b,c,a),select.setCursorPos(this.container,c),webkitLastLineHack(this.container))},cursorCoords:function(a,b){function c(a,c){var d=-(document.body.scrollTop||document.documentElement.scrollTop||0),e=-(document.body.scrollLeft||document.documentElement.scrollLeft||0)+
c;forEach([a,b?null:window.frameElement],function(a){for(;a;)e+=a.offsetLeft,d+=a.offsetTop,a=a.offsetParent});return{x:e,y:d,yBot:d+a.offsetHeight}}function d(a,b){var c=document.createElement("SPAN");c.appendChild(document.createTextNode(a));try{return b(c)}finally{c.parentNode&&c.parentNode.removeChild(c)}}var f=select.cursorPos(this.container,a);if(!f)return null;for(var e=f.offset,g=f.node,h=this;e;){g=g?g.nextSibling:this.container.firstChild;f=nodeText(g);if(e<f.length)return d(f.substr(0,
e),function(a){a.style.position="absolute";a.style.visibility="hidden";a.className=g.className;h.container.appendChild(a);return c(g,a.offsetWidth)});e-=f.length}return g&&isSpan(g)?c(g,g.offsetWidth):g&&g.nextSibling&&isSpan(g.nextSibling)?c(g.nextSibling,0):d("\u200b",function(a){g?g.parentNode.insertBefore(a,g.nextSibling):h.container.insertBefore(a,h.container.firstChild);return c(a,0)})},reroutePasteEvent:function(){if(!this.capturingPaste&&!(window.opera||gecko&&20101026<=gecko)){this.capturingPaste=
!0;var a=window.frameElement.CodeMirror.textareaHack,b=this.cursorCoords(!0,!0);a.style.top=b.y+"px";if(internetExplorer&&(b=select.getBookmark(this.container)))this.selectionSnapshot=b;parent.focus();a.value="";a.focus();var c=this;parent.setTimeout(function(){c.capturingPaste=!1;window.focus();c.selectionSnapshot&&window.select.setBookmark(c.container,c.selectionSnapshot);var b=a.value;b&&(c.replaceSelection(b),select.scrollToCursor(c.container))},10)}},replaceRange:function(a,b,c){c=asEditorLines(c);
c[0]=this.history.textAfter(a.node).slice(0,a.offset)+c[0];var d=c[c.length-1];c[c.length-1]=d+this.history.textAfter(b.node).slice(b.offset);b=this.history.nodeAfter(b.node);this.history.push(a.node,b,c);return{node:this.history.nodeBefore(b),offset:d.length}},getSearchCursor:function(a,b,c){return new q(this,a,b,c)},reindent:function(){this.container.firstChild&&this.indentRegion(null,this.container.lastChild)},reindentSelection:function(a){if(select.somethingSelected()){var b=select.selectionTopNode(this.container,
!0),c=select.selectionTopNode(this.container,!1);!1===b||!1===c||this.indentRegion(b,c,a,!0)}else this.indentAtCursor(a)},grabKeys:function(a,b){this.frozen=a;this.keyFilter=b},ungrabKeys:function(){this.frozen="leave"},setParser:function(a,b){o.Parser=window[a];(b=b||this.options.parserConfig)&&o.Parser.configure&&o.Parser.configure(b);this.container.firstChild&&(forEach(this.container.childNodes,function(a){3!=a.nodeType&&(a.dirty=!0)}),this.addDirtyNode(this.firstChild),this.scheduleHighlight())},
keyDown:function(a){"leave"==this.frozen&&(this.keyFilter=this.frozen=null);if(this.frozen&&(!this.keyFilter||this.keyFilter(a.keyCode,a)))a.stop(),this.frozen(a);else{var b=a.keyCode;this.delayScanning();this.options.autoMatchParens&&this.scheduleParenHighlight();if(13==b)a.ctrlKey&&!a.altKey?this.reparseBuffer():(select.insertNewlineAtCursor(),b=this.options.enterMode,"flat"!=b&&this.indentAtCursor("keep"==b?"keep":void 0),select.scrollToCursor(this.container)),a.stop();else if(9==b&&"default"!=
this.options.tabMode&&!a.ctrlKey)this.handleTab(!a.shiftKey),a.stop();else if(32==b&&a.shiftKey&&"default"==this.options.tabMode)this.handleTab(!0),a.stop();else if(36==b&&!a.shiftKey&&!a.ctrlKey)this.home()&&a.stop();else if(35==b&&!a.shiftKey&&!a.ctrlKey)this.end()&&a.stop();else if(33==b&&!a.shiftKey&&!a.ctrlKey&&!gecko)this.pageUp()&&a.stop();else if(34==b&&!a.shiftKey&&!a.ctrlKey&&!gecko)this.pageDown()&&a.stop();else if((219==b||221==b)&&a.ctrlKey&&!a.altKey)this.highlightParens(a.shiftKey,
!0),a.stop();else if(a.metaKey&&!a.shiftKey&&(37==b||39==b)){var c=select.selectionTopNode(this.container);!1!==c&&this.container.firstChild&&(37==b?select.focusAfterNode(l(c),this.container):(b=p(c,this.container),select.focusAfterNode(b?b.previousSibling:this.container.lastChild,this.container)),a.stop())}else if((a.ctrlKey||a.metaKey)&&!a.altKey)a.shiftKey&&90==b||89==b?(select.scrollToNode(this.history.redo()),a.stop()):90==b||safari&&8==b?(select.scrollToNode(this.history.undo()),a.stop()):83==
b&&this.options.saveFunction?(this.options.saveFunction(),a.stop()):86==b&&!mac&&this.reroutePasteEvent()}},keyPress:function(a){var b=this.options.electricChars&&o.Parser.electricChars,c=this;if(this.frozen&&(!this.keyFilter||this.keyFilter(a.keyCode||a.code,a))||13==a.code||9==a.code&&"default"!=this.options.tabMode||32==a.code&&a.shiftKey&&"default"==this.options.tabMode)a.stop();else if(mac&&(a.ctrlKey||a.metaKey)&&"v"==a.character)this.reroutePasteEvent();else if(b&&-1!=b.indexOf(a.character))parent.setTimeout(function(){c.indentAtCursor(null)},
0);else if(brokenOpera)if(8==a.code){var d=select.selectionTopNode(this.container),c=this,f=d?d.nextSibling:this.container.firstChild;!1!==d&&f&&isBR(f)&&parent.setTimeout(function(){select.selectionTopNode(c.container)==f&&select.focusAfterNode(f.previousSibling,c.container)},20)}else 46==a.code&&(d=select.selectionTopNode(this.container),c=this,d&&isBR(d)&&parent.setTimeout(function(){select.selectionTopNode(c.container)!=d&&select.focusAfterNode(d,c.container)},20));else if(slowWebkit&&(f=(d=select.selectionTopNode(this.container))?
d.nextSibling:this.container.firstChild,d&&f&&isBR(f)&&!isBR(d))){var e=document.createTextNode("\u200b");this.container.insertBefore(e,f);parent.setTimeout(function(){"\u200b"==e.nodeValue?removeElement(e):e.nodeValue=e.nodeValue.replace("\u200b","")},20)}webkit&&!this.options.textWrapping&&setTimeout(function(){var a=select.selectionTopNode(c.container,!0);a&&3==a.nodeType&&a.previousSibling&&isBR(a.previousSibling)&&a.nextSibling&&isBR(a.nextSibling)&&a.parentNode.replaceChild(document.createElement("BR"),
a.previousSibling)},50)},keyUp:function(a){this.cursorActivity(16<=a.keyCode&&18>=a.keyCode||33<=a.keyCode&&40>=a.keyCode)},indentLineAfter:function(a,b){function c(a){a=a?a.nextSibling:d.container.firstChild;return!a||!hasClass(a,"whitespace")?null:a}var d=this,f=c(a),e=0,g=f?f.currentText.length:0,h=f?f.nextSibling:a?a.nextSibling:this.container.firstChild;if("keep"==b){if(a){var i=c(l(a.previousSibling));i&&(e=i.currentText.length)}}else i=a&&h&&h.currentText?h.currentText:"",null!=b&&"indent"!=
this.options.tabMode?e=b?g+indentUnit:Math.max(0,g-indentUnit):a?e=a.indentation(i,g,b,h):o.Parser.firstIndentation&&(e=o.Parser.firstIndentation(i,g,b,h));g=e-g;0>g?0==e?(h&&select.snapshotMove(f.firstChild,h.firstChild||h,0),removeElement(f),f=null):(select.snapshotMove(f.firstChild,f.firstChild,g,!0),f.currentText=makeWhiteSpace(e),f.firstChild.nodeValue=f.currentText):0<g?f?(f.currentText=makeWhiteSpace(e),f.firstChild.nodeValue=f.currentText,select.snapshotMove(f.firstChild,f.firstChild,g,!0)):
(f=makePartSpan(makeWhiteSpace(e)),f.className="whitespace",a?insertAfter(f,a):this.container.insertBefore(f,this.container.firstChild),select.snapshotMove(h&&(h.firstChild||h),f.firstChild,e,!1,!0)):f&&select.snapshotMove(f.firstChild,f.firstChild,e,!1);0!=g&&this.addDirtyNode(a)},highlightAtCursor:function(){var a=select.selectionTopNode(this.container,!0),b=select.selectionTopNode(this.container,!1);if(!1===a||!1===b)return!1;select.markSelection();if(!1===this.highlight(a,p(b,this.container),
!0,20))return!1;select.selectMarked();return!0},handleTab:function(a){"spaces"==this.options.tabMode&&!select.somethingSelected()?select.insertTabAtCursor():this.reindentSelection(a)},home:function(){var a=select.selectionTopNode(this.container,!0),b=a;if(!1===a||a&&!a.isPart&&!isBR(a)||!this.container.firstChild)return!1;for(;a&&!isBR(a);)a=a.previousSibling;var c=a?a.nextSibling:this.container.firstChild;c&&c!=b&&c.isPart&&hasClass(c,"whitespace")?select.focusAfterNode(c,this.container):select.focusAfterNode(a,
this.container);select.scrollToCursor(this.container);return!0},end:function(){var a=select.selectionTopNode(this.container,!0);if(!1===a)return!1;a=p(a,this.container);if(!a)return!1;select.focusAfterNode(a.previousSibling,this.container);select.scrollToCursor(this.container);return!0},pageUp:function(){var a=this.cursorPosition().line,b=this.visibleLineCount();if(!1===a||!1===b)return!1;for(var b=b-2,c=0;c<b&&!(a=this.prevLine(a),!1===a);c++);if(0==c)return!1;select.setCursorPos(this.container,
{node:a,offset:0});select.scrollToCursor(this.container);return!0},pageDown:function(){var a=this.cursorPosition().line,b=this.visibleLineCount();if(!1===a||!1===b)return!1;for(var b=b-2,c=0;c<b;c++){var d=this.nextLine(a);if(!1===d)break;a=d}if(0==c)return!1;select.setCursorPos(this.container,{node:a,offset:0});select.scrollToCursor(this.container);return!0},scheduleParenHighlight:function(){this.parenEvent&&parent.clearTimeout(this.parenEvent);var a=this;this.parenEvent=parent.setTimeout(function(){a.highlightParens()},
300)},highlightParens:function(a,b){function c(a,b){a&&(h?h.call?h(a,b):a.className+=" "+h[b?0:1]:(a.style.fontWeight="bold",a.style.color=b?"#8F8":"#F88"))}function d(a){a&&(h&&!h.call?removeClass(removeClass(a,h[0]),h[1]):g.options.unmarkParen?g.options.unmarkParen(a):(a.style.fontWeight="",a.style.color=""))}function f(a){if(a.currentText)return(a=a.currentText.match(/^[\s\u00a0]*([\(\)\[\]{}])[\s\u00a0]*$/))&&a[1]}function e(){for(var a=[],b,c=!0,d=j;d;d=l?d.nextSibling:d.previousSibling)if(d.className==
k&&isSpan(d)&&(b=f(d))){if(/[\(\[\{]/.test(b)==l?a.push(b):a.length?a.pop()!=matching[b]&&(c=!1):c=!1,!a.length)break}else if(d.dirty||!isSpan(d)&&!isBR(d))return{node:d,status:"dirty"};return{node:d,status:d&&c}}var g=this,h=this.options.markParen;"string"==typeof h&&(h=[h,h]);!b&&g.highlighted&&(d(g.highlighted[0]),d(g.highlighted[1]));if(window&&window.parent&&window.select){this.parenEvent&&parent.clearTimeout(this.parenEvent);this.parenEvent=null;var i,j=select.selectionTopNode(this.container,
!0);if(j&&this.highlightAtCursor()&&(j=select.selectionTopNode(this.container,!0))&&((i=f(j))||(j=j.nextSibling)&&(i=f(j))))for(var k=j.className,l=/[\(\[\{]/.test(i);;){var n=e();if("dirty"==n.status)this.highlight(n.node,p(n.node)),n.node.dirty=!1;else{c(j,n.status);c(n.node,n.status);b?parent.setTimeout(function(){d(j);d(n.node)},500):g.highlighted=[j,n.node];a&&n.node&&select.focusAfterNode(n.node.previousSibling,this.container);break}}}},indentAtCursor:function(a){if(this.container.firstChild&&
this.highlightAtCursor()){var b=select.selectionTopNode(this.container,!1);!1!==b&&(select.markSelection(),this.indentLineAfter(l(b),a),select.selectMarked())}},indentRegion:function(a,b,c,d){var f=a=l(a),e=a&&l(a.previousSibling);isBR(b)||(b=p(b,this.container));this.addDirtyNode(a);do{var g=p(f,this.container);f&&this.highlight(e,g,!0);this.indentLineAfter(f,c);e=f;f=g}while(f!=b);d&&select.setCursorPos(this.container,{node:a,offset:0},{node:b,offset:0})},cursorActivity:function(a){this.unloaded&&
(window.document.designMode="off",window.document.designMode="on",this.unloaded=!1);if(internetExplorer){this.container.createTextRange().execCommand("unlink");clearTimeout(this.saveSelectionSnapshot);var b=this;this.saveSelectionSnapshot=setTimeout(function(){var a=select.getBookmark(b.container);if(a)b.selectionSnapshot=a},200)}var c=this.options.onCursorActivity;if(!a||c){var d=select.selectionTopNode(this.container,!1);!1!==d&&this.container.firstChild&&(d=d||this.container.firstChild,c&&c(d),
a||(this.scheduleHighlight(),this.addDirtyNode(d)))}},reparseBuffer:function(){forEach(this.container.childNodes,function(a){a.dirty=!0});this.container.firstChild&&this.addDirtyNode(this.container.firstChild)},addDirtyNode:function(a){if(a=a||this.container.firstChild){for(var b=0;b<this.dirty.length;b++)if(this.dirty[b]==a)return;3!=a.nodeType&&(a.dirty=!0);this.dirty.push(a)}},allClean:function(){return!this.dirty.length},scheduleHighlight:function(){var a=this;parent.clearTimeout(this.highlightTimeout);
this.highlightTimeout=parent.setTimeout(function(){a.highlightDirty()},this.options.passDelay)},getDirtyNode:function(){for(;0<this.dirty.length;){var a=this.dirty.pop();try{for(;a&&a.parentNode!=this.container;)a=a.parentNode;if(a&&(a.dirty||3==a.nodeType))return a}catch(b){}}return null},highlightDirty:function(a){if(!window||!window.parent||!window.select)return!1;this.options.readOnly||select.markSelection();for(var b,c=a?null:(new Date).getTime()+this.options.passTime;((new Date).getTime()<c||
a)&&(b=this.getDirtyNode());){var d=this.highlight(b,c);d&&d.node&&d.dirty&&this.addDirtyNode(d.node.nextSibling)}this.options.readOnly||select.selectMarked();b&&this.scheduleHighlight();return 0==this.dirty.length},documentScanner:function(a){var b=this,c=null;return function(){if(window&&window.parent&&window.select){c&&c.parentNode!=b.container&&(c=null);select.markSelection();var d=b.highlight(c,(new Date).getTime()+a,!0);select.selectMarked();d=d?d.node&&d.node.nextSibling:null;c=c==d?null:d;
b.delayScanning()}}},delayScanning:function(){this.scanner&&(parent.clearTimeout(this.documentScan),this.documentScan=parent.setTimeout(this.scanner,this.options.continuousScanning))},highlight:function(a,b,c,d){function f(a){if(a){var b=a.oldNextSibling;(n||void 0===b||a.nextSibling!=b)&&g.history.touch(a);a.oldNextSibling=a.nextSibling}else b=g.container.oldFirstChild,(n||void 0===b||g.container.firstChild!=b)&&g.history.touch(null),g.container.oldFirstChild=g.container.firstChild}var e=this.container,
g=this,h=this.options.activeTokens,i="number"==typeof b?b:null;if(!e.firstChild)return!1;for(;a&&(!a.parserFromHere||a.dirty);){if(null!=d&&isBR(a)&&0>--d)return!1;a=a.previousSibling}if(a&&!a.nextSibling)return!1;var j=k(a?a.nextSibling:e.firstChild),d=stringStream(j),l=a?a.parserFromHere(d):o.Parser.make(d),p={current:null,get:function(){this.current||(this.current=j.nodes.shift());return this.current},next:function(){this.current=null},remove:function(){e.removeChild(this.get());this.current=null},
getNonEmpty:function(){for(var a=this.get();a&&isSpan(a)&&""==a.currentText;)if(window.opera&&(null==a.previousSibling||isBR(a.previousSibling))&&(null==a.nextSibling||isBR(a.nextSibling)))this.next(),a=this.get();else{var b=a;this.remove();a=this.get();select.snapshotMove(b.firstChild,a&&(a.firstChild||a),0)}return a}},n=!1,q=!0,r=0;forEach(l,function(d){var m=p.getNonEmpty();if("\n"==d.value){if(!isBR(m))throw"Parser out of sync. Expected BR.";if(m.dirty||!m.indentation)n=!0;f(a);a=m;m.parserFromHere=
l.copy();m.indentation=d.indentation||alwaysZero;m.dirty=!1;if(null==i&&m==b)throw StopIteration;if(null!=i&&(new Date).getTime()>=i||!n&&!q&&1<r&&!c)throw StopIteration;q=n;n=!1;r=0;p.next()}else{if(!isSpan(m))throw"Parser out of sync. Expected SPAN.";m.dirty&&(n=!0);r++;if(!m.reduced&&m.currentText==d.value&&m.className==d.style)h&&m.dirty&&h(m,d,g),m.dirty=!1,p.next();else{n=!0;var j=makePartSpan(d.value);j.className=d.style;e.insertBefore(j,m);h&&h(j,d,g);for(var d=d.value.length,k=0;0<d;){var m=
p.get(),o=m.currentText.length;select.snapshotReplaceNode(m.firstChild,j.firstChild,d,k);o>d?(m.currentText=m.currentText.substring(d),m.reduced=!0,d=0):(d-=o,k+=o,p.remove())}}}});f(a);webkitLastLineHack(this.container);return{node:p.getNonEmpty(),dirty:n}}};return o}();addEventHandler(window,"load",function(){var i=window.frameElement.CodeMirror;i.editor=new Editor(i.options);parent.setTimeout(method(i,"init"),0)});

var select={};
(function(){function l(a,b){for(;a&&a.parentNode!=b;)a=a.parentNode;return a}function s(a,b){for(;!a.previousSibling&&a.parentNode!=b;)a=a.parentNode;return l(a.previousSibling,b)}function p(a){var b=a.nextSibling;if(b){for(;b.firstChild;)b=b.firstChild;return 3==b.nodeType||isBR(b)?b:p(b)}for(a=a.parentNode;a&&!a.nextSibling;)a=a.parentNode;return a&&p(a)}select.ie_selection=document.selection&&document.selection.createRangeCollection;select.scrollToNode=function(a,b){if(a){for(var c=a,d=document.body,
e=document.documentElement,g=!c.nextSibling||!c.nextSibling.nextSibling||!c.nextSibling.nextSibling.nextSibling,i=0;c&&!c.offsetTop;)i++,c=c.previousSibling;0==i&&(g=!1);if(!webkit||!c||!(5==c.offsetTop&&5==c.offsetLeft)){for(var i=i*(c?c.offsetHeight:0),h=0,n=a?a.offsetWidth:0;c&&c.offsetParent;)i+=c.offsetTop,isBR(c)||(h+=c.offsetLeft),c=c.offsetParent;var c=d.scrollLeft||e.scrollLeft||0,d=d.scrollTop||e.scrollTop||0,f=!1,j=window.innerWidth||e.clientWidth||0;if(b||n<j){if(b){var l=select.offsetInNode(a),
q=nodeText(a).length;q&&(h+=n*(l/q))}n=h-c;if(0>n||n>j)c=h,f=!0}h=i-d;if(0>h||g||h>(window.innerHeight||e.clientHeight||0)-50)d=g?1E6:i,f=!0;f&&window.scrollTo(c,d)}}};select.scrollToCursor=function(a){select.scrollToNode(select.selectionTopNode(a,!0)||a.firstChild,!0)};var f=null;select.snapshotChanged=function(){f&&(f.changed=!0)};select.snapshotReplaceNode=function(a,b,c,d){function e(e){a==e.node?(f.changed=!0,c&&e.offset>c?e.offset-=c:(e.node=b,e.offset+=d||0)):select.ie_selection&&0==e.offset&&
e.node==p(a)&&(f.changed=!0)}f&&(e(f.start),e(f.end))};select.snapshotMove=function(a,b,c,d,e){function g(g){if(a==g.node&&(!e||0==g.offset))f.changed=!0,g.node=b,g.offset=d?Math.max(0,g.offset+c):c}f&&(g(f.start),g(f.end))};if(select.ie_selection){var j=function(){var a=document.selection;return!a?null:a.createRange?a.createRange():a.createTextRange()},t=function(a){function b(a){for(var b=null;!b&&a;)b=a.nextSibling,a=a.parentNode;return c(b)}function c(a){for(;a&&a.firstChild;)a=a.firstChild;return{node:a,
offset:0}}var d=j();d.collapse(a);a=d.parentElement();if(!isAncestor(document.body,a))return null;if(!a.firstChild)return c(a);var e=d.duplicate();e.moveToElementText(a);e.collapse(!0);for(var g=a.firstChild;g;g=g.nextSibling){if(3==g.nodeType){var i=g.nodeValue.length;e.move("character",i)}else e.moveToElementText(g),e.collapse(!1);var h=d.compareEndPoints("StartToStart",e);if(0==h)return b(g);if(1!=h){if(3!=g.nodeType)return c(g);e.setEndPoint("StartToEnd",d);return{node:g,offset:i-e.text.length}}}return b(a)};
select.markSelection=function(){f=null;if(document.selection){var a=t(!0),b=t(!1);a&&b&&(f={start:a,end:b,changed:!1})}};select.selectMarked=function(){function a(a){var c=document.body.createTextRange(),b=a.node;if(b)if(3==b.nodeType){c.moveToElementText(b.parentNode);for(a=a.offset;b.previousSibling;)b=b.previousSibling,a+=(b.innerText||"").length;c.move("character",a)}else c.moveToElementText(b),c.collapse(!0);else c.moveToElementText(document.body),c.collapse(!1);return c}if(f&&f.changed){var b=
a(f.start),c=a(f.end);b.setEndPoint("StartToEnd",c);b.select()}};select.offsetInNode=function(a){var b=j();if(!b)return 0;var c=b.duplicate();try{c.moveToElementText(a)}catch(d){return 0}b.setEndPoint("StartToStart",c);return b.text.length};select.selectionTopNode=function(a,b){var c=j();if(!c)return!1;var d=c.duplicate();c.collapse(b);var e=c.parentElement();if(e&&isAncestor(a,e)&&(d.moveToElementText(e),1==c.compareEndPoints("StartToStart",d)))return l(e,a);b=0;for(e=a.childNodes.length-1;b<e;){var g=
Math.ceil((e+b)/2),i=a.childNodes[g];if(!i)return!1;var h;a:{h=d;if(3==i.nodeType){for(var f=0,k=i.previousSibling;k&&3==k.nodeType;)f+=k.nodeValue.length,k=k.previousSibling;if(k){try{h.moveToElementText(k)}catch(m){h=!1;break a}h.collapse(!1)}else h.moveToElementText(i.parentNode);f&&h.move("character",f)}else try{h.moveToElementText(i)}catch(o){h=!1;break a}h=!0}if(!h)return!1;1==c.compareEndPoints("StartToStart",d)?b=g:e=g-1}if(0==b){c=j();d=c.duplicate();try{d.moveToElementText(a)}catch(q){return null}if(0==
c.compareEndPoints("StartToStart",d))return null}return a.childNodes[b]||null};select.focusAfterNode=function(a,b){var c=document.body.createTextRange();c.moveToElementText(a||b);c.collapse(!a);c.select()};select.somethingSelected=function(){var a=j();return a&&""!=a.text};var u=function(a){var b=j();b&&(b.pasteHTML(a),b.collapse(!1),b.select())};select.insertNewlineAtCursor=function(){u("<br>")};select.insertTabAtCursor=function(){u("\u00a0\u00a0\u00a0\u00a0")};select.cursorPos=function(a,b){var c=
j();if(!c)return null;for(var d=select.selectionTopNode(a,b);d&&!isBR(d);)d=d.previousSibling;var e=c.duplicate();c.collapse(b);if(d)e.moveToElementText(d),e.collapse(!1);else{try{e.moveToElementText(a)}catch(g){return null}e.collapse(!0)}c.setEndPoint("StartToStart",e);return{node:d,offset:c.text.length}};select.setCursorPos=function(a,b,c){function d(c){var b=document.body.createTextRange();c.node?(b.moveToElementText(c.node),b.collapse(!1)):(b.moveToElementText(a),b.collapse(!0));b.move("character",
c.offset);return b}var e=d(b);c&&c!=b&&e.setEndPoint("EndToEnd",d(c));e.select()};select.getBookmark=function(a){var b=select.cursorPos(a,!0),a=select.cursorPos(a,!1);if(b&&a)return{from:b,to:a}};select.setBookmark=function(a,b){b&&select.setCursorPos(a,b.from,b.to)}}else{var r=function(a,b){for(;3!=a.nodeType&&!isBR(a);){for(var c=a.childNodes[b]||a.nextSibling,b=0;!c&&a.parentNode;)a=a.parentNode,c=a.nextSibling;a=c;if(!c)break}return{node:a,offset:b}};select.markSelection=function(){var a=window.getSelection();
if(!a||0==a.rangeCount)return f=null;a=a.getRangeAt(0);f={start:r(a.startContainer,a.startOffset),end:r(a.endContainer,a.endOffset),changed:!1}};select.selectMarked=function(){function a(){if(c.start.node==c.end.node&&c.start.offset==c.end.offset){var a=window.getSelection();if(!a||0==a.rangeCount)return!0;a=a.getRangeAt(0);a=r(a.startContainer,a.startOffset);return c.start.node!=a.node||c.start.offset!=a.offset}}function b(a,b){if(a.node)if(0==a.offset)d["set"+b+"Before"](a.node);else d["set"+b](a.node,
a.offset);else d.setStartAfter(document.body.lastChild||document.body)}var c=f;if(c&&(c.changed||webkit&&a())){var d=document.createRange();b(c.end,"End");b(c.start,"Start");o(d)}};var o=function(a){var b=window.getSelection();b&&(b.removeAllRanges(),b.addRange(a))},m=function(){var a=window.getSelection();return!a||0==a.rangeCount?!1:a.getRangeAt(0)};select.selectionTopNode=function(a,b){var c=m();if(!c)return!1;var d=b?c.startContainer:c.endContainer,e=b?c.startOffset:c.endOffset;window.opera&&
!b&&c.endContainer==a&&c.endOffset==c.startOffset+1&&a.childNodes[c.startOffset]&&isBR(a.childNodes[c.startOffset])&&e--;return 3==d.nodeType?0<e?l(d,a):s(d,a):"HTML"==d.nodeName.toUpperCase()?1==e?null:a.lastChild:d==a?0==e?null:d.childNodes[e-1]:e==d.childNodes.length?l(d,a):0==e?s(d,a):l(d.childNodes[e-1],a)};select.focusAfterNode=function(a,b){var c=document.createRange();c.setStartBefore(b.firstChild||b);a&&!a.firstChild?c.setEndAfter(a):a?c.setEnd(a,a.childNodes.length):c.setEndBefore(b.firstChild||
b);c.collapse(!1);o(c)};select.somethingSelected=function(){var a=m();return a&&!a.collapsed};select.offsetInNode=function(a){var b=m();if(!b)return 0;b=b.cloneRange();b.setStartBefore(a);return b.toString().length};select.insertNodeAtCursor=function(a){var b=m();if(b){b.deleteContents();b.insertNode(a);webkitLastLineHack(document.body);if(window.opera&&isBR(a)&&isSpan(a.parentNode)){var b=a.nextSibling,c=a.parentNode,d=c.parentNode;d.insertBefore(a,c.nextSibling);for(c="";b&&3==b.nodeType;b=b.nextSibling)c+=
b.nodeValue,removeElement(b);d.insertBefore(makePartSpan(c,document),a.nextSibling)}b=document.createRange();b.selectNode(a);b.collapse(!1);o(b)}};select.insertNewlineAtCursor=function(){select.insertNodeAtCursor(document.createElement("BR"))};select.insertTabAtCursor=function(){select.insertNodeAtCursor(document.createTextNode("\u00a0\u00a0\u00a0\u00a0"))};select.cursorPos=function(a,b){var c=m();if(c){for(var d=select.selectionTopNode(a,b);d&&!isBR(d);)d=d.previousSibling;c=c.cloneRange();c.collapse(b);
d?c.setStartAfter(d):c.setStartBefore(a);return{node:d,offset:c.toString().length}}};select.setCursorPos=function(a,b,c){function d(b,c,d){function f(a){3==a.nodeType?k.push(a):forEach(a.childNodes,f)}if(0==c&&b&&!b.nextSibling)return e["set"+d+"After"](b),!0;if(b=b?b.nextSibling:a.firstChild){if(0==c)return e["set"+d+"Before"](b),!0;for(var k=[];;){for(;b&&!k.length;)f(b),b=b.nextSibling;var j=k.shift();if(!j)return!1;var l=j.nodeValue.length;if(l>=c)return e["set"+d](j,c),!0;c-=l}}}var e=document.createRange(),
c=c||b;d(c.node,c.offset,"End")&&d(b.node,b.offset,"Start")&&o(e)}}})();

var stringStream=function(g){function e(){for(;c==a.length;){d+=a;a="";c=0;try{a=g.next()}catch(b){if(b!=StopIteration)throw b;return!1}}return!0}var a="",c=0,d="";return{peek:function(){return!e()?null:a.charAt(c)},next:function(){if(!e()){if(0<d.length)throw"End of stringstream reached without emptying buffer ('"+d+"').";throw StopIteration;}return a.charAt(c++)},get:function(){var b=d;d="";0<c&&(b+=a.slice(0,c),a=a.slice(c),c=0);return b},push:function(b){a=a.slice(0,c)+b+a.slice(c)},lookAhead:function(b,
h,f,m){function i(b){return m?b.toLowerCase():b}var b=i(b),j=!1,e=d,n=c;for(f&&this.nextWhileMatches(/[\s\u00a0]/);;){var f=c+b.length,k=a.length-c;if(f<=a.length){j=b==i(a.slice(c,f));c=f;break}else if(b.slice(0,k)==i(a.slice(c))){d+=a;a="";try{a=g.next()}catch(l){if(l!=StopIteration)throw l;break}c=0;b=b.slice(k)}else break}if(!j||!h)a=d.slice(e.length)+a,c=n,d=e;return j},lookAheadRegex:function(b,h){if("^"!=b.source.charAt(0))throw Error("Regexps passed to lookAheadRegex must start with ^");for(;-1==
a.indexOf("\n",c);)try{a+=g.next()}catch(d){if(d!=StopIteration)throw d;break}var e=a.slice(c).match(b);e&&h&&(c+=e[0].length);return e},more:function(){return null!==this.peek()},applies:function(b){var a=this.peek();return null!==a&&b(a)},nextWhile:function(b){for(var a;null!==(a=this.peek())&&b(a);)this.next()},matches:function(b){var a=this.peek();return null!==a&&b.test(a)},nextWhileMatches:function(b){for(var a;null!==(a=this.peek())&&b.test(a);)this.next()},equals:function(a){return a===this.peek()},
endOfLine:function(){var a=this.peek();return null==a||"\n"==a}}};

function tokenizer(b,e){function c(a){return"\n"!=a&&/^[\s\u00a0]*$/.test(a)}var d={state:e,take:function(a){"string"==typeof a&&(a={style:a,type:a});a.content=(a.content||"")+b.get();/\n$/.test(a.content)||b.nextWhile(c);a.value=a.content+b.get();return a},next:function(){if(!b.more())throw StopIteration;var a;if(b.equals("\n"))return b.next(),this.take("whitespace");if(b.applies(c))a="whitespace";else for(;!a;)a=this.state(b,function(a){d.state=a});return this.take(a)}};return d};

function UndoHistory(a,b,c,g){this.container=a;this.maxDepth=b;this.commitDelay=c;this.editor=g;this.last=this.first=a={text:"",from:null,to:null};this.firstTouched=!1;this.history=[];this.redoHistory=[];this.touched=[];this.lostundo=0}
UndoHistory.prototype={scheduleCommit:function(){var a=this;parent.clearTimeout(this.commitTimeout);this.commitTimeout=parent.setTimeout(function(){a.tryCommit()},this.commitDelay)},touch:function(a){this.setTouched(a);this.scheduleCommit()},undo:function(){this.commit();if(this.history.length){var a=this.history.pop();this.redoHistory.push(this.updateTo(a,"applyChain"));this.notifyEnvironment();return this.chainNode(a)}},redo:function(){this.commit();if(this.redoHistory.length){var a=this.redoHistory.pop();
this.addUndoLevel(this.updateTo(a,"applyChain"));this.notifyEnvironment();return this.chainNode(a)}},clear:function(){this.history=[];this.redoHistory=[];this.lostundo=0},historySize:function(){return{undo:this.history.length,redo:this.redoHistory.length,lostundo:this.lostundo}},push:function(a,b,c){for(var g=[],e=0;e<c.length;e++){var f=e==c.length-1?b:document.createElement("br");g.push({from:a,to:f,text:cleanText(c[e])});a=f}this.pushChains([g],null==a&&null==b);this.notifyEnvironment()},pushChains:function(a,
b){this.commit(b);this.addUndoLevel(this.updateTo(a,"applyChain"));this.redoHistory=[]},chainNode:function(a){for(var b=0;b<a.length;b++){var c=a[b][0];if(c=c&&(c.from||c.to))return c}},reset:function(){this.history=[];this.redoHistory=[];this.lostundo=0},textAfter:function(a){return this.after(a).text},nodeAfter:function(a){return this.after(a).to},nodeBefore:function(a){return this.before(a).from},tryCommit:function(){window&&window.parent&&window.UndoHistory&&(this.editor.highlightDirty()?this.commit(!0):
this.scheduleCommit())},commit:function(a){parent.clearTimeout(this.commitTimeout);a||this.editor.highlightDirty(!0);a=this.touchedChains();a.length&&(this.addUndoLevel(this.updateTo(a,"linkChain")),this.redoHistory=[],this.notifyEnvironment())},updateTo:function(a,b){for(var c=[],g=[],e=0;e<a.length;e++)c.push(this.shadowChain(a[e])),g.push(this[b](a[e]));"applyChain"==b&&this.notifyDirty(g);return c},notifyDirty:function(a){forEach(a,method(this.editor,"addDirtyNode"));this.editor.scheduleHighlight()},
notifyEnvironment:function(){if(this.onChange)this.onChange(this.editor);window.frameElement&&window.frameElement.CodeMirror.updateNumbers&&window.frameElement.CodeMirror.updateNumbers()},linkChain:function(a){for(var b=0;b<a.length;b++){var c=a[b];c.from?c.from.historyAfter=c:this.first=c;c.to?c.to.historyBefore=c:this.last=c}},after:function(a){return a?a.historyAfter:this.first},before:function(a){return a?a.historyBefore:this.last},setTouched:function(a){a?a.historyTouched||(this.touched.push(a),
a.historyTouched=!0):this.firstTouched=!0},addUndoLevel:function(a){this.history.push(a);this.history.length>this.maxDepth&&(this.history.shift(),lostundo+=1)},touchedChains:function(){function a(a){for(var b=[],d=a?a.nextSibling:c.container.firstChild;d&&(!isBR(d)||d.hackBR);d=d.nextSibling)!d.hackBR&&d.currentText&&b.push(d.currentText);return{from:a,to:d,text:cleanText(b.join(""))}}function b(a,c){for(var d=c+"Sibling",b=a[d];b&&!isBR(b);)b=b[d];return b}var c=this,g=null,e=[];c.firstTouched&&
c.touched.push(null);forEach(c.touched,function(b){if(!b||!(b.parentNode!=c.container||b.hackBR)){b?b.historyTouched=!1:c.firstTouched=!1;var f=a(b),d=c.after(b);if(!d||d.text!=f.text||d.to!=f.to)e.push(f),b?b.historyTemp=f:g=f}});var f=[];c.touched=[];forEach(e,function(e){if(e.from?e.from.historyTemp:g){for(var h=[],d=e.from,j=!0;;){var i=d?d.historyTemp:g;if(!i)if(j)break;else i=a(d);h.unshift(i);d?d.historyTemp=null:g=null;if(!d)break;j=c.after(d);d=b(d,"previous")}d=e.to;for(j=c.before(e.from);d;){i=
d?d.historyTemp:g;if(!i)if(j)break;else i=a(d);h.push(i);d?d.historyTemp=null:g=null;j=c.before(d);d=b(d,"next")}f.push(h)}});return f},shadowChain:function(a){for(var b=[],c=this.after(a[0].from),a=a[a.length-1].to;!(b.push(c),c=c.to,!c||c==a);)c=c.historyAfter||this.before(a);return b},applyChain:function(a){for(var b=select.cursorPos(this.container,!1),c=a[0].from,g=a[a.length-1].to,e=c?c.nextSibling:this.container.firstChild;e!=g;){var f=e.nextSibling;removeElement(e);e=f}for(e=0;e<a.length;e++)if(f=
a[e],0<e&&this.container.insertBefore(f.from,g),this.container.insertBefore(makePartSpan(fixSpaces(f.text)),g),b&&b.node==f.from){var k=0,h=this.after(f.from);if(h&&e==a.length-1){for(var d=0;d<b.offset&&f.text.charAt(d)==h.text.charAt(d);d++);b.offset>d&&(k=f.text.length-h.text.length)}select.setCursorPos(this.container,{node:f.from,offset:Math.max(0,b.offset+k)})}else b&&e==a.length-1&&b.node&&b.node.parentNode!=this.container&&select.setCursorPos(this.container,{node:f.from,offset:f.text.length});
this.linkChain(a);return c}};

function method(a,b){return function(){a[b].apply(a,arguments)}}var StopIteration={toString:function(){return"StopIteration"}};function forEach(a,b){if(a.next)try{for(;;)b(a.next())}catch(c){if(c!=StopIteration)throw c;}else for(var d=0;d<a.length;d++)b(a[d])}function map(a,b){var c=[];forEach(a,function(a){c.push(b(a))});return c}function matcher(a){return function(b){return a.test(b)}}function hasClass(a,b){var c=a.className;return c&&RegExp("(^| )"+b+"($| )").test(c)}
function removeClass(a,b){a.className=a.className.replace(RegExp(" "+b+"\\b","g"),"");return a}function insertAfter(a,b){b.parentNode.insertBefore(a,b.nextSibling);return a}function removeElement(a){a.parentNode&&a.parentNode.removeChild(a)}function clearElement(a){for(;a.firstChild;)a.removeChild(a.firstChild)}function isAncestor(a,b){for(;b=b.parentNode;)if(a==b)return!0;return!1}var nbsp="\u00a0",matching={"{":"}","[":"]","(":")","}":"{","]":"[",")":"("};
function normalizeEvent(a){a.stopPropagation||(a.stopPropagation=function(){this.cancelBubble=!0},a.preventDefault=function(){this.returnValue=!1});a.stop||(a.stop=function(){this.stopPropagation();this.preventDefault()});"keypress"==a.type&&(a.code=null==a.charCode?a.keyCode:a.charCode,a.character=String.fromCharCode(a.code));return a}
function addEventHandler(a,b,c,d){function e(a){c(normalizeEvent(a||window.event))}if("function"==typeof a.addEventListener){if(a.addEventListener(b,e,!1),d)return function(){a.removeEventListener(b,e,!1)}}else if(a.attachEvent("on"+b,e),d)return function(){a.detachEvent("on"+b,e)}}function nodeText(a){return a.textContent||a.innerText||a.nodeValue||""}function nodeTop(a){for(var b=0;a.offsetParent;)b+=a.offsetTop,a=a.offsetParent;return b}function isBR(a){a=a.nodeName;return"BR"==a||"br"==a}
function isSpan(a){a=a.nodeName;return"SPAN"==a||"span"==a};

var SqlParser=Editor.Parser=function(){function j(a){return RegExp("^(?:"+a.join("|")+")$","i")}function g(a){return function(c){c=c&&c.charAt(0);c=a&&c==a.type;return a?a.align?a.col-(c?a.width:0):a.indent+(c?0:indentUnit):0}}var h=j("abs,acos,adddate,aes_encrypt,aes_decrypt,ascii,asin,atan,atan2,avg,benchmark,bin,bit_and,bit_count,bit_length,bit_or,cast,ceil,ceiling,char_length,character_length,coalesce,concat,concat_ws,connection_id,conv,convert,cos,cot,count,curdate,current_date,current_time,current_timestamp,current_user,curtime,database,date_add,date_format,date_sub,dayname,dayofmonth,dayofweek,dayofyear,decode,degrees,des_encrypt,des_decrypt,elt,encode,encrypt,exp,export_set,extract,field,find_in_set,floor,format,found_rows,from_days,from_unixtime,get_lock,greatest,group_unique_users,hex,ifnull,inet_aton,inet_ntoa,instr,interval,is_free_lock,isnull,last_insert_id,lcase,least,left,length,ln,load_file,locate,log,log2,log10,lower,lpad,ltrim,make_set,master_pos_wait,max,md5,mid,min,mod,monthname,now,nullif,oct,octet_length,ord,password,period_add,period_diff,pi,position,pow,power,quarter,quote,radians,rand,release_lock,repeat,reverse,right,round,rpad,rtrim,sec_to_time,session_user,sha,sha1,sign,sin,soundex,space,sqrt,std,stddev,strcmp,subdate,substring,substring_index,sum,sysdate,system_user,tan,time_format,time_to_sec,to_days,trim,ucase,unique_users,unix_timestamp,upper,user,version,week,weekday,yearweek".split(",")),
f=j("alter,grant,revoke,primary,key,table,start,top,transaction,select,update,insert,delete,create,describe,from,into,values,where,join,inner,left,natural,and,or,in,not,xor,like,using,on,order,group,by,asc,desc,limit,offset,union,all,as,distinct,set,commit,rollback,replace,view,database,separator,if,exists,null,truncate,status,show,lock,unique,having,drop,procedure,begin,end,delimiter,call,else,leave,declare,temporary,then,definer,event,schedule,comment,enable,disable,slave".split(",")),n=j("bigint,binary,bit,blob,bool,char,character,date,datetime,dec,decimal,double,enum,float,float4,float8,int,int1,int2,int3,int4,int8,integer,long,longblob,longtext,mediumblob,mediumint,mediumtext,middleint,nchar,numeric,real,set,smallint,text,time,timestamp,tinyblob,tinyint,tinytext,varbinary,varchar,year".split(",")),
i=j(":=,<,<=,==,<>,>,>=,like,rlike,in,xor,between".split(",")),k=/[*+\-<>=&|:\/]/,l={},m=function(){function a(d,a){var b=d.next();if("@"==b||"$"==b)return d.nextWhileMatches(/[\w\d]/),"sql-var";if("["==b)return a(c(b)),null;if('"'==b||"'"==b||"`"==b)return a(g(b)),null;if(","==b||";"==b)return"sql-separator";if("#"==b){for(;!d.endOfLine();)d.next();return"sql-comment"}if("-"==b){if("-"==d.peek()){for(;!d.endOfLine();)d.next();return"sql-comment"}return/\d/.test(d.peek())?(d.nextWhileMatches(/\d/),
"."==d.peek()&&(d.next(),d.nextWhileMatches(/\d/)),"sql-number"):"sql-operator"}if(k.test(b)){if("/"==b&&"*"==d.peek())return a(e("sql-comment","*/")),null;d.nextWhileMatches(k);return"sql-operator"}if(/\d/.test(b))return d.nextWhileMatches(/\d/),"."==d.peek()&&(d.next(),d.nextWhileMatches(/\d/)),"sql-number";if(/[()]/.test(b))return"sql-punctuation";d.nextWhileMatches(/[_\w\d]/);b=d.get();return{style:i.test(b)?"sql-operator":f.test(b)?"sql-keyword":h.test(b)?"sql-function":n.test(b)?"sql-type":
"sql-word",content:b}}function c(){return function(d,c){for(;!d.endOfLine();)if("]"==d.next()){c(a);break}return"sql-word"}}function g(d){return function(c,b){for(var e=!1;!c.endOfLine();){var g=c.next();if(g==d&&!e){b(a);break}e="T-SQL"==l.extension?!e&&d==g&&c.equals(d):!e&&"\\"==g}return"`"==d?"sql-quoted-word":"sql-literal"}}function e(d,c){return function(b,e){for(;!b.endOfLine();){if(b.lookAhead(c,!0)){e(a);break}b.next()}return d}}return function(d,c){return tokenizer(d,c||a)}}();return{make:function(a){function c(c,
b,a){e={prev:e,indent:d,col:f,type:c,width:b,align:a}}var h=m(a),e=null,d=0,f=0,b={next:function(){var b=h.next(),a=b.style,i=b.content,j=b.value.length;"\n"==i?(b.indentation=g(e),d=f=0,e&&null==e.align&&(e.align=!1)):"whitespace"==a&&0==f?d=j:!e&&"sql-comment"!=a&&c(";",0,!1);"\n"!=i&&(f+=j);"sql-punctuation"==a?"("==i?c(")",j):")"==i&&(e=e.prev):"sql-separator"==a&&";"==i&&e&&!e.prev&&(e=e.prev);return b},copy:function(){var a=e,c=d,g=f,i=h.state;return function(j){h=m(j,i);e=a;d=c;f=g;return b}}};
return b},electricChars:")",configure:function(a){for(var c in a)a.hasOwnProperty(c)&&(l[c]=a[c])}}}(),StopIteration={toString:function(){return"StopIteration"}},indentUnit=2;
(function(){function j(g){for(var h="",f=0;f<indentUnit;f++)h+=" ";for(var g=g.replace(/\t/g,h).replace(/\u00a0/g," ").replace(/\r\n?/g,"\n"),j=0,i=[],g=g.split("\n"),h=0;h<g.length;h++)0!=h&&i.push("\n"),i.push(g[h]);return{next:function(){if(j<i.length)return i[j++];throw StopIteration;}}}window.highlightSql=function(g,h,f){parser=(SqlParser||Editor.Parser).make(stringStream(j(f)));var n=1;callback=function(a){h.append(document.createTextNode(""+n++));h.append(document.createElement("BR"));for(var c=
0;c<a.length;c++)g.append(a[c]);g.append(document.createElement("BR"))};f=[];if(1==callback.nodeType){var i=callback;callback=function(a){for(var c=0;c<a.length;c++)i.appendChild(a[c]);i.appendChild(document.createElement("br"))}}try{for(;;){var k=parser.next();if("\n"==k.value)callback(f),f=[];else{var l=document.createElement("span");l.className=k.style;l.appendChild(document.createTextNode(k.value));f.push(l)}}}catch(m){if(m!=StopIteration)throw m;}f.length&&callback(f)}})();

