/*
    http://mywebsql.net/license
*/
function wrkfrmSubmit(a,b,c,f){document.frmquery?(frm=document.frmquery,$("#popup_overlay").removeClass("ui-helper-hidden")):(xfrm=getFrame(),frm=xfrm.document.frmquery,xfrm.onerror=frameErrorHandler,setPageStatus(!0));frm.type.value=a;frm.id.value=b;frm.name.value=c;frm.query.value=f;4>=arguments.length?frm.submit():(callback=arguments[4],data="q=wrkfrm&"+$(frm).serialize(),$.ajax({type:"POST",url:"?",data:data,success:callback}))}
function getFrame(){xfrm=null;return xfrm=$.browser.msie&&9>$.browser.version?document.frames("wrkfrm"):window.frames.wrkfrm}function resetFrame(){xfrm=getFrame();xfrm.src="javascript:false"}function debugMsg(a){$("#messageContainer").innerHTML=a}function frameErrorHandler(){setPageStatus(!1);$("#recordCounter").html("&nbsp;");$("#timeCounter").html("");$("#messageContainer").html("Navigation Error. Try reloading the page")}
function setPageStatus(a,b){a?($("#nav_bar").css("display","none"),$("#loader").css("display","table"),showNavBtns()):($("#loader").css("display","none"),$("#nav_bar").css("display","table"),showNavBtns("query","queryall"));b&&$("#messageContainer").html(b)}
function addCmdHistory(a){d=new Date;h=d.getHours();m=d.getMinutes();10>h&&(h="0"+h);10>m&&(m="0"+m);$("#sql-history > tbody:last").append('<tr><td valign="top" class="dt">['+h+":"+m+']</td><td class="hst">'+a+";</td></tr>");1<arguments.length&&!0==arguments[1]&&(currentQuery=a)}function str_replace(a,b,c){for(var c=""+c,f=is_array(b),e=is_array(c),a=[].concat(a),b=[].concat(b),g=(c=[].concat(c)).length;j=0,g--;)for(;c[g]=c[g].split(a[j]).join(f?b[j]||"":b[0]),++j in a;);return e?c:c[0]}
function is_array(a){return a instanceof Array}Array.indexOf||(Array.prototype.indexOf=function(a){for(var b=0;b<this.length;b++)if(this[b]==a)return b;return-1});function __(a){return window.lang&&window.lang[a]?window.lang[a]:a}function formatBytes(a){if(a<1024)return a+" B";return size=a<1048576?number_format(a/1024)+" KB":number_format(a/1048576,2)+" MB"}
function number_format(a,b,c,f){var a=(a+"").replace(/[^0-9+\-Ee.]/g,""),a=!isFinite(+a)?0:+a,b=!isFinite(+b)?0:Math.abs(b),f=typeof f==="undefined"?",":f,c=typeof c==="undefined"?".":c,e="",e=(b?function(a,b){var c=Math.pow(10,b);return""+Math.round(a*c)/c}(a,b):""+Math.round(a)).split(".");e[0].length>3&&(e[0]=e[0].replace(/\B(?=(?:\d{3})+(?!\d))/g,f));if((e[1]||"").length<b){e[1]=e[1]||"";e[1]=e[1]+Array(b-e[1].length+1).join("0")}return e.join(c)}
function htmlchars(a,b,c,f){var e=c=0,g=false;if(typeof b==="undefined"||b===null)b=2;a=a.toString();f!==false&&(a=a.replace(/&/g,"&amp;"));a=a.replace(/</g,"&lt;").replace(/>/g,"&gt;");f={ENT_NOQUOTES:0,ENT_HTML_QUOTE_SINGLE:1,ENT_HTML_QUOTE_DOUBLE:2,ENT_COMPAT:2,ENT_QUOTES:3,ENT_IGNORE:4};b===0&&(g=true);if(typeof b!=="number"){b=[].concat(b);for(e=0;e<b.length;e++)f[b[e]]===0?g=true:f[b[e]]&&(c=c|f[b[e]]);b=c}b&f.ENT_HTML_QUOTE_SINGLE&&(a=a.replace(/'/g,"&#039;"));g||(a=a.replace(/"/g,"&quot;"));
return a};
