/*
 jquery.layout 1.3.0 - Release Candidate 29.8
 $Date: 2010-09-27 08:00:00 (Mon, 27 Sep 2010) $
 $Rev: 30298 $

 Copyright (c) 2010 
 Fabrizio Balliano (http://www.fabrizioballiano.net)
 Kevin Dalman (http://allpro.net)

 Dual licensed under the GPL (http://www.gnu.org/licenses/gpl.html)
 and MIT (http://www.opensource.org/licenses/mit-license.php) licenses.

 Docs: http://layout.jquery-dev.net/documentation.html
 Tips: http://layout.jquery-dev.net/tips.html
 Help: http://groups.google.com/group/jquery-ui-layout
*/
(function(f){var t=f.browser;f.layout={browser:{mozilla:t.mozilla,webkit:t.webkit||t.safari||!1,msie:t.msie,isIE6:t.msie&&6==t.version,boxModel:!1},scrollbarWidth:function(){return window.scrollbarWidth||f.layout.getScrollbarSize("width")},scrollbarHeight:function(){return window.scrollbarHeight||f.layout.getScrollbarSize("height")},getScrollbarSize:function(h){var o=f('<div style="position: absolute; top: -10000px; left: -10000px; width: 100px; height: 100px; overflow: scroll;"></div>').appendTo("body"),
p={width:o.width()-o[0].clientWidth,height:o.height()-o[0].clientHeight};o.remove();window.scrollbarWidth=p.width;window.scrollbarHeight=p.height;return h.match(/^(width|height)$/i)?p[h]:p},showInvisibly:function(h,o){if(!h)return{};h.jquery||(h=f(h));var p={display:h.css("display"),visibility:h.css("visibility")};return o||"none"==p.display?(h.css({display:"block",visibility:"hidden"}),p):{}},getElemDims:function(h){var o={},p=o.css={},r={},E,t,v=h.offset();o.offsetLeft=v.left;o.offsetTop=v.top;
f.each(["Left","Right","Top","Bottom"],function(w,v){E=p["border"+v]=f.layout.borderWidth(h,v);t=p["padding"+v]=f.layout.cssNum(h,"padding"+v);r[v]=E+t;o["inset"+v]=t});o.offsetWidth=h.innerWidth();o.offsetHeight=h.innerHeight();o.outerWidth=h.outerWidth();o.outerHeight=h.outerHeight();o.innerWidth=o.outerWidth-r.Left-r.Right;o.innerHeight=o.outerHeight-r.Top-r.Bottom;p.width=h.width();p.height=h.height();return o},getElemCSS:function(f,o){var p={},r=f[0].style,t=o.split(","),G=["Top","Bottom","Left",
"Right"],v=["Color","Style","Width"],w,F,K,U,Y,V;for(U=0;U<t.length;U++)if(w=t[U],w.match(/(border|padding|margin)$/))for(Y=0;4>Y;Y++)if(F=G[Y],"border"==w)for(V=0;3>V;V++)K=v[V],p[w+F+K]=r[w+F+K];else p[w+F]=r[w+F];else p[w]=r[w];return p},cssWidth:function(h,o){var p=f.layout.borderWidth,r=f.layout.cssNum;if(0>=o)return 0;if(!f.layout.browser.boxModel)return o;p=o-p(h,"Left")-p(h,"Right")-r(h,"paddingLeft")-r(h,"paddingRight");return 0<p?p:0},cssHeight:function(h,o){var p=f.layout.borderWidth,r=
f.layout.cssNum;if(0>=o)return 0;if(!f.layout.browser.boxModel)return o;p=o-p(h,"Top")-p(h,"Bottom")-r(h,"paddingTop")-r(h,"paddingBottom");return 0<p?p:0},cssNum:function(h,o){h.jquery||(h=f(h));var p=f.layout.showInvisibly(h),r=parseInt(f.curCSS(h[0],o,!0),10)||0;h.css(p);return r},borderWidth:function(h,o){h.jquery&&(h=h[0]);var p="border"+o.substr(0,1).toUpperCase()+o.substr(1);return"none"==f.curCSS(h,p+"Style",!0)?0:parseInt(f.curCSS(h,p+"Width",!0),10)||0}};f.fn.layout=function(h){var o,p,
r,t,G,v,w,F,K,U;function Y(a){if(!a)return!0;var b=a.keyCode;if(33>b)return!0;var c={38:"north",40:"south",37:"west",39:"east"},e=a.shiftKey,d=a.ctrlKey,m,g,i,k;d&&37<=b&&40>=b&&n[c[b]].enableCursorHotkey?k=c[b]:(d||e)&&f.each(j.borderPanes.split(","),function(a,c){m=n[c];g=m.customHotkey;i=m.customHotkeyModifier;if(e&&"SHIFT"==i||d&&"CTRL"==i||d&&e)if(g&&b==(isNaN(g)||9>=g?g.toUpperCase().charCodeAt(0):g))return k=c,!1});if(!k||!s[k]||!n[k].closable||l[k].isHidden)return!0;Z(k);a.stopPropagation();
return a.returnValue=!1}function V(a){this&&this.tagName&&(a=this);var b;H(a)?b=s[a]:f(a).data("layoutRole")?b=f(a):f(a).parents().each(function(){if(f(this).data("layoutRole"))return b=f(this),!1});if(b&&b.length){var c=b.data("layoutEdge"),a=l[c];a.cssSaved&&ia(c);if(a.isSliding||a.isResizing||a.isClosed)a.cssSaved=!1;else{var e={zIndex:j.zIndex.pane_normal+2},d={},m=b.css("overflow"),g=b.css("overflowX"),i=b.css("overflowY");"visible"!=m&&(d.overflow=m,e.overflow="visible");g&&!g.match(/visible|auto/)&&
(d.overflowX=g,e.overflowX="visible");i&&!i.match(/visible|auto/)&&(d.overflowY=g,e.overflowY="visible");a.cssSaved=d;b.css(e);f.each(j.allPanes.split(","),function(a,b){b!=c&&ia(b)})}}}function ia(a){this&&this.tagName&&(a=this);var b;H(a)?b=s[a]:f(a).data("layoutRole")?b=f(a):f(a).parents().each(function(){if(f(this).data("layoutRole"))return b=f(this),!1});if(b&&b.length){var a=b.data("layoutEdge"),a=l[a],c=a.cssSaved||{};!a.isSliding&&!a.isResizing&&b.css("zIndex",j.zIndex.pane_normal);b.css(c);
a.cssSaved=!1}}function ja(a,b,c){var e=f(a);if(e.length)if(-1==j.borderPanes.indexOf(b))alert(o+r.toLowerCase()+": "+b);else return a=n[b].buttonClass+"-"+c,e.addClass(a+" "+a+"-"+b).data("layoutName",n.name),e;else alert(o+p+": "+a);return null}function Ca(a,b,c){switch(b.toLowerCase()){case "toggle":oa(a,c);break;case "open":pa(a,c);break;case "close":Da(a,c);break;case "pin":Ea(a,c);break;case "toggle-slide":oa(a,c,!0);break;case "open-slide":pa(a,c,!0)}}function oa(a,b,c){(a=ja(a,b,"toggle"))&&
a.click(function(a){Z(b,!!c);a.stopPropagation()})}function pa(a,b,c){(a=ja(a,b,"open"))&&a.attr("title",t).click(function(a){P(b,!!c);a.stopPropagation()})}function Da(a,b){var c=ja(a,b,"close");c&&c.attr("title",G).click(function(a){L(b);a.stopPropagation()})}function Ea(a,b){var c=ja(a,b,"pin");if(c){var e=l[b];c.click(function(a){qa(f(this),b,e.isSliding||e.isClosed);e.isSliding||e.isClosed?P(b):L(b);a.stopPropagation()});qa(c,b,!e.isClosed&&!e.isSliding);j[b].pins.push(a)}}function ra(a,b){f.each(j[a].pins,
function(c,e){qa(f(e),a,b)})}function qa(a,b,c){var e=a.attr("pin");if(!(e&&c==("down"==e))){var e=n[b].buttonClass+"-pin",d=e+"-"+b,b=e+"-up "+d+"-up",e=e+"-down "+d+"-down";a.attr("pin",c?"down":"up").attr("title",c?v:w).removeClass(c?b:e).addClass(c?e:b)}}function Fa(a){for(var a=f.extend({},n.cookie,a||{}).name||n.name||"Layout",b=document.cookie,b=b?b.split(";"):[],c,e=0,d=b.length;e<d;e++)if(c=f.trim(b[e]).split("="),c[0]==a)return Ga(decodeURIComponent(c[1]));return""}function sa(a,b){var c=
f.extend({},n.cookie,b||{}),e=c.name||n.name||"Layout",d="",m="",g=!1;c.expires.toUTCString?m=c.expires:"number"==typeof c.expires&&(m=new Date,0<c.expires?m.setDate(m.getDate()+c.expires):(m.setYear(1970),g=!0));m&&(d+=";expires="+m.toUTCString());c.path&&(d+=";path="+c.path);c.domain&&(d+=";domain="+c.domain);c.secure&&(d+=";secure");g?(l.cookie={},document.cookie=e+"="+d):(l.cookie=ta(a||c.keys),document.cookie=e+"="+encodeURIComponent(Ha(l.cookie))+d);return f.extend({},l.cookie)}function Ia(a){if(a=
Fa(a))l.cookie=f.extend({},a),Ja(a);return a}function Ja(a){f.extend(!0,n,a)}function ta(a){var b={},c={isClosed:"initClosed",isHidden:"initHidden"},e,d,m;a||(a=n.cookie.keys);f.isArray(a)&&(a=a.join(","));for(var a=a.replace(/__/g,".").split(","),g=0,i=a.length;g<i;g++)e=a[g].split("."),d=e[0],e=e[1],0>j.allPanes.indexOf(d)||(m=l[d][e],void 0!=m&&("isClosed"==e&&l[d].isSliding&&(m=!0),(b[d]||(b[d]={}))[c[e]?c[e]:e]=m));return b}function Ha(a){function b(a){var e=[],d=0,f,g,i;for(f in a)g=a[f],i=
typeof g,"string"==i?g='"'+g+'"':"object"==i&&(g=b(g)),e[d++]='"'+f+'":'+g;return"{"+e.join(",")+"}"}return b(a)}function Ga(a){try{return window.eval("("+a+")")||{}}catch(b){return{}}}r=__("Pane");t=__("Open");G=__("Close");F=__("Resize");K=__("Slide Open");w=__("Pin");v=__("Un-Pin");p=__("selector");U=__("Not enough room to show this pane.");o="Error Adding Button \n\nInvalid ";var n={name:"",scrollToBookmarkOnLoad:!0,resizeWithWindow:!0,resizeWithWindowDelay:200,resizeWithWindowMaxDelay:0,onresizeall_start:null,
onresizeall_end:null,onload:null,onunload:null,autoBindCustomButtons:!1,zIndex:null,defaults:{applyDemoStyles:!1,closable:!0,resizable:!0,slidable:!0,initClosed:!1,initHidden:!1,contentSelector:".ui-layout-content",contentIgnoreSelector:".ui-layout-ignore",findNestedContent:!1,paneClass:"ui-layout-pane",resizerClass:"ui-layout-resizer",togglerClass:"ui-layout-toggler",buttonClass:"ui-layout-button",minSize:0,maxSize:0,spacing_open:6,spacing_closed:6,togglerLength_open:50,togglerLength_closed:50,togglerAlign_open:"center",
togglerAlign_closed:"center",togglerTip_open:G,togglerTip_closed:t,togglerContent_open:"",togglerContent_closed:"",resizerDblClickToggle:!0,autoResize:!0,autoReopen:!0,resizerDragOpacity:1,maskIframesOnResize:!0,resizeNestedLayout:!0,resizeWhileDragging:!1,resizeContentWhileDragging:!1,noRoomToOpenTip:U,resizerTip:F,sliderTip:K,sliderCursor:"pointer",slideTrigger_open:"click",slideTrigger_close:"mouseleave",hideTogglerOnSlide:!1,preventQuickSlideClose:!(!f.browser.webkit&&!f.browser.safari),showOverflowOnHover:!1,
enableCursorHotkey:!0,customHotkeyModifier:"SHIFT",fxName:"slide",fxSpeed:null,fxSettings:{},fxOpacityFix:!0,triggerEventsOnLoad:!1,triggerEventsWhileDragging:!0,onshow_start:null,onshow_end:null,onhide_start:null,onhide_end:null,onopen_start:null,onopen_end:null,onclose_start:null,onclose_end:null,onresize_start:null,onresize_end:null,onsizecontent_start:null,onsizecontent_end:null,onswap_start:null,onswap_end:null,ondrag_start:null,ondrag_end:null},north:{paneSelector:".ui-layout-north",size:"auto",
resizerCursor:"n-resize",customHotkey:""},south:{paneSelector:".ui-layout-south",size:"auto",resizerCursor:"s-resize",customHotkey:""},east:{paneSelector:".ui-layout-east",size:200,resizerCursor:"e-resize",customHotkey:""},west:{paneSelector:".ui-layout-west",size:200,resizerCursor:"w-resize",customHotkey:""},center:{paneSelector:".ui-layout-center",minWidth:0,minHeight:0},useStateCookie:!1,cookie:{name:"",autoSave:!0,autoLoad:!0,domain:"",path:"",expires:"",secure:!1,keys:"north.size,south.size,east.size,west.size,north.isClosed,south.isClosed,east.isClosed,west.isClosed,north.isHidden,south.isHidden,east.isHidden,west.isHidden"}},
ua={slide:{all:{duration:"fast"},north:{direction:"up"},south:{direction:"down"},east:{direction:"right"},west:{direction:"left"}},drop:{all:{duration:"slow"},north:{direction:"up"},south:{direction:"down"},east:{direction:"right"},west:{direction:"left"}},scale:{all:{duration:"fast"}}},l={id:"layout"+(new Date).getTime(),initialized:!1,container:{},north:{},south:{},east:{},west:{},center:{},cookie:{}},j={allPanes:"north,south,west,east,center",borderPanes:"north,south,west,east",altSide:{north:"south",
south:"north",east:"west",west:"east"},hidden:{visibility:"hidden"},visible:{visibility:"visible"},zIndex:{pane_normal:1,resizer_normal:2,iframe_mask:2,pane_sliding:100,pane_animate:1E3,resizer_drag:1E4},resizers:{cssReq:{position:"absolute",padding:0,margin:0,fontSize:"1px",textAlign:"left",overflow:"hidden"},cssDemo:{background:"#DDD",border:"none"}},togglers:{cssReq:{position:"absolute",display:"block",padding:0,margin:0,overflow:"hidden",textAlign:"center",fontSize:"1px",cursor:"pointer",zIndex:1},
cssDemo:{background:"#AAA"}},content:{cssReq:{},cssDemo:{overflow:"auto",padding:"10px"},cssDemoPane:{overflow:"hidden",padding:0}},panes:{cssReq:{position:"absolute",margin:0},cssDemo:{padding:"10px",background:"#FFF",border:"1px solid #BBB",overflow:"auto"}},north:{side:"Top",sizeType:"Height",dir:"horz",cssReq:{top:0,bottom:"auto",left:0,right:0,width:"auto"},pins:[]},south:{side:"Bottom",sizeType:"Height",dir:"horz",cssReq:{top:"auto",bottom:0,left:0,right:0,width:"auto"},pins:[]},east:{side:"Right",
sizeType:"Width",dir:"vert",cssReq:{left:"auto",right:0,top:"auto",bottom:"auto",height:"auto"},pins:[]},west:{side:"Left",sizeType:"Width",dir:"vert",cssReq:{left:0,right:"auto",top:"auto",bottom:"auto",height:"auto"},pins:[]},center:{dir:"center",cssReq:{left:"auto",right:"auto",top:"auto",bottom:"auto",height:"auto",width:"auto"}}},D={data:{},set:function(a,b,c){D.clear(a);D.data[a]=setTimeout(b,c)},clear:function(a){var b=D.data;b[a]&&(clearTimeout(b[a]),delete b[a])}},H=function(a){try{return"string"==
typeof a||"object"==typeof a&&null!==a.constructor.toString().match(/string/i)}catch(b){return!1}},y=function(a,b){return Math.max(a,b)},Wa=function(a){var b,c={cookie:{},defaults:{fxSettings:{}},north:{fxSettings:{}},south:{fxSettings:{}},east:{fxSettings:{}},west:{fxSettings:{}},center:{fxSettings:{}}},a=a||{};a.effects||a.cookie||a.defaults||a.north||a.south||a.west||a.east||a.center?c=f.extend(!0,c,a):f.each(a,function(a,d){b=a.split("__");if(!b[1]||c[b[0]])c[b[1]?b[0]:"defaults"][b[1]?b[1]:b[0]]=
d});return c},Ka=function(a,b,c){function e(m){var g=j[m];g.doCallback?(d.push(m),m=g.callback.split(",")[1],m!=b&&0<=!f.inArray(m,d)&&e(m)):(g.doCallback=!0,g.callback=a+","+b+","+(c?1:0))}var d=[];f.each(j.borderPanes.split(","),function(a,b){if(j[b].isMoving)return e(b),!1})},La=function(a){a=j[a];j.isLayoutBusy=!1;delete a.isMoving;if(a.doCallback&&a.callback){a.doCallback=!1;var b=a.callback.split(","),c=0<b[2]?!0:!1;"open"==b[0]?P(b[1],c):"close"==b[0]&&L(b[1],c);a.doCallback||(a.callback=null)}},
x=function(a,b){if(b){var c;try{if("function"==typeof b)c=b;else if(H(b))if(b.match(/,/)){var e=b.split(",");c=eval(e[0]);if("function"==typeof c&&1<e.length)return c(e[1])}else c=eval(b);else return;if("function"==typeof c)return a&&s[a]?c(a,s[a],f.extend({},l[a]),n[a],n.name):c(Ma,f.extend({},l),n,n.name)}catch(d){}}},Na=function(a,b){if(!a)return{};a.jquery||(a=f(a));var c={display:a.css("display"),visibility:a.css("visibility")};return b||"none"==c.display?(a.css({display:"block",visibility:"hidden"}),
c):{}},Oa=function(a){if(!l.browser.mozilla){var b=s[a];"IFRAME"==l[a].tagName?b.css(j.hidden).css(j.visible):b.find("IFRAME").css(j.hidden).css(j.visible)}},W=function(a,b){a.jquery||(a=f(a));var c=Na(a),e=parseInt(f.curCSS(a[0],b,!0),10)||0;a.css(c);return e},ca=function(a,b){a.jquery&&(a=a[0]);var c="border"+b.substr(0,1).toUpperCase()+b.substr(1);return"none"==f.curCSS(a,c+"Style",!0)?0:parseInt(f.curCSS(a,c+"Width",!0),10)||0},I=function(a,b){var c=H(a),e=c?s[a]:f(a);isNaN(b)&&(b=c?M(a):e.outerWidth());
if(0>=b)return 0;if(!l.browser.boxModel)return b;c=b-ca(e,"Left")-ca(e,"Right")-W(e,"paddingLeft")-W(e,"paddingRight");return 0<c?c:0},J=function(a,b){var c=H(a),e=c?s[a]:f(a);isNaN(b)&&(b=c?M(a):e.outerHeight());if(0>=b)return 0;if(!l.browser.boxModel)return b;c=b-ca(e,"Top")-ca(e,"Bottom")-W(e,"paddingTop")-W(e,"paddingBottom");return 0<c?c:0},ka=function(a){var b=j[a].dir,a={minWidth:1001-I(a,1E3),minHeight:1001-J(a,1E3)};"horz"==b&&(a.minSize=a.minHeight);"vert"==b&&(a.minSize=a.minWidth);return a},
Xa=function(a,b,c){var e=a;H(a)?e=s[a]:a.jquery||(e=f(a));a=J(e,b);e.css({height:a,visibility:"visible"});0<a&&0<e.innerWidth()?c&&e.data("autoHidden")&&(e.show().data("autoHidden",!1),l.browser.mozilla||e.css(j.hidden).css(j.visible)):c&&!e.data("autoHidden")&&e.hide().data("autoHidden",!0)},Q=function(a,b,c){c||(c=j[a].dir);H(b)&&b.match(/%/)&&(b=parseInt(b,10)/100);if(0===b)return 0;if(1<=b)return parseInt(b,10);if(0<b){var a=n,e;"horz"==c?e=u.innerHeight-(s.north?a.north.spacing_open:0)-(s.south?
a.south.spacing_open:0):"vert"==c&&(e=u.innerWidth-(s.west?a.west.spacing_open:0)-(s.east?a.east.spacing_open:0));return Math.floor(e*b)}if("center"==a)return 0;e=s[a];var c="horz"==c?"height":"width",a=Na(e),d=e.css(c);e.css(c,"auto");b="height"==c?e.outerHeight():e.outerWidth();e.css(c,d).css(a);return b},M=function(a,b){var c=s[a],e=n[a],d=l[a],f=b?e.spacing_open:0,e=b?e.spacing_closed:0;return!c||d.isHidden?0:d.isClosed||d.isSliding&&b?e:"horz"==j[a].dir?c.outerHeight()+f:c.outerWidth()+f},N=
function(a,b){var c=n[a],e=l[a],d=j[a],f=d.dir;d.side.toLowerCase();d.sizeType.toLowerCase();var d=void 0!=b?b:e.isSliding,g=c.spacing_open,i=j.altSide[a],k=l[i],h=s[i],q=!h||!1===k.isVisible||k.isSliding?0:"horz"==f?h.outerHeight():h.outerWidth(),i=(!h||k.isHidden?0:n[i][!1!==k.isClosed?"spacing_closed":"spacing_open"])||0,k="horz"==f?u.innerHeight:u.innerWidth,h=ka("center"),h="horz"==f?y(n.center.minHeight,h.minHeight):y(n.center.minWidth,h.minWidth),d=k-g-(d?0:Q("center",h,f)+q+i),f=e.minSize=
y(Q(a,c.minSize),ka(a).minSize),g=c.maxSize?Q(a,c.maxSize):1E5,d=Math.min(g,d),d=e.maxSize=d,e=e.resizerPosition={},g=u.insetTop,q=u.insetLeft,i=u.innerWidth,k=u.innerHeight,c=c.spacing_open;switch(a){case "north":e.min=g+f;e.max=g+d;break;case "west":e.min=q+f;e.max=q+d;break;case "south":e.min=g+k-d-c;e.max=g+k-f-c;break;case "east":e.min=q+i-d-c,e.max=q+i-f-c}},X=function(a){var b={},c=b.css={},e={},d,m,g=a.offset();b.offsetLeft=g.left;b.offsetTop=g.top;f.each(["Left","Right","Top","Bottom"],function(f,
g){d=c["border"+g]=ca(a,g);m=c["padding"+g]=W(a,"padding"+g);e[g]=d+m;b["inset"+g]=m});b.offsetWidth=a.innerWidth();b.offsetHeight=a.innerHeight();b.outerWidth=a.outerWidth();b.outerHeight=a.outerHeight();b.innerWidth=b.outerWidth-e.Left-e.Right;b.innerHeight=b.outerHeight-e.Top-e.Bottom;c.width=a.width();c.height=a.height();return b},va=function(a,b){var c={},e=a[0].style,d=b.split(","),f=["Top","Bottom","Left","Right"],g=["Color","Style","Width"],i,k,h,j,l,n;for(j=0;j<d.length;j++)if(i=d[j],i.match(/(border|padding|margin)$/))for(l=
0;4>l;l++)if(k=f[l],"border"==i)for(n=0;3>n;n++)h=g[n],c[i+k+h]=e[i+k+h];else c[i+k]=e[i+k];else c[i]=e[i];return c},wa=function(a,b){var c=f(a),e=c.data("layoutRole"),d=c.data("layoutEdge"),m=n[d][e+"Class"],d="-"+d,g=c.hasClass(m+"-closed")?"-closed":"-open",i="-closed"==g?"-open":"-closed",g=m+"-hover "+(m+d+"-hover ")+(m+g+"-hover ")+(m+d+g+"-hover ");b&&(g+=m+i+"-hover "+(m+d+i+"-hover "));"resizer"==e&&c.hasClass(m+"-sliding")&&(g+=m+"-sliding-hover "+(m+d+"-sliding-hover "));return f.trim(g)},
da=function(a,b){var c=b||this;f(c).addClass(wa(c))},O=function(a,b){var c=b||this;f(c).removeClass(wa(c,!0))},Ya=function(a){f("body").disableSelection();da(a,this)},Pa=function(a,b){var c=b||this,e=f(c).data("layoutEdge"),d=e+"ResizerLeave";D.clear(d);b?l[e].isResizing||f("body").enableSelection():(O(a,this),D.set(d,function(){Pa(a,c)},200))},Za=function(){var a=Number(n.resizeWithWindowDelay)||100;0<a&&(D.clear("winResize"),D.set("winResize",function(){D.clear("winResize");D.clear("winResizeRepeater");
la()},a),D.data.winResizeRepeater||Qa())},Qa=function(){var a=Number(n.resizeWithWindowMaxDelay);0<a&&D.set("winResizeRepeater",function(){Qa();la()},a)},Ra=function(){var a=n;l.cookie=ta();a.useStateCookie&&a.cookie.autoSave&&sa();x(null,a.onunload)},$a=function(){f.each(j.borderPanes.split(","),function(a,b){var c=n[b];if(c.enableCursorHotkey||c.customHotkey)return f(document).bind("keydown."+z,Y),!1})},ab=function(){function a(a){for(var c in b)void 0!=a[c]&&(a[b[c]]=a[c],delete a[c])}h=Wa(h);
var b={applyDefaultStyles:"applyDemoStyles"};a(h.defaults);f.each(j.allPanes.split(","),function(b,c){a(h[c])});h.effects&&(f.extend(ua,h.effects),delete h.effects);f.extend(n.cookie,h.cookie);f.each("name,zIndex,scrollToBookmarkOnLoad,resizeWithWindow,resizeWithWindowDelay,resizeWithWindowMaxDelay,onresizeall,onresizeall_start,onresizeall_end,onload,onunload,autoBindCustomButtons,useStateCookie".split(","),function(a,b){if(h[b]!==void 0)n[b]=h[b];else if(h.defaults[b]!==void 0){n[b]=h.defaults[b];
delete h.defaults[b]}});f.each(["paneSelector","resizerCursor","customHotkey"],function(a,b){delete h.defaults[b]});f.extend(!0,n.defaults,h.defaults);j.center=f.extend(!0,{},j.panes,j.center);var c=n.zIndex;if(0===c||0<c)j.zIndex.pane_normal=c,j.zIndex.resizer_normal=c+1,j.zIndex.iframe_mask=c+1;f.extend(n.center,h.center);var e=f.extend(!0,{},n.defaults,h.defaults,n.center);f.each("paneClass,contentSelector,applyDemoStyles,triggerEventsOnLoad,showOverflowOnHover,onresize,onresize_start,onresize_end,resizeNestedLayout,resizeContentWhileDragging,onsizecontent,onsizecontent_start,onsizecontent_end".split(","),
function(a,b){n.center[b]=e[b]});var d,m=n.defaults;f.each(j.borderPanes.split(","),function(a,b){j[b]=f.extend(true,{},j.panes,j[b]);d=n[b]=f.extend(true,{},n.defaults,n[b],h.defaults,h[b]);if(!d.paneClass)d.paneClass="ui-layout-pane";if(!d.resizerClass)d.resizerClass="ui-layout-resizer";if(!d.togglerClass)d.togglerClass="ui-layout-toggler";f.each(["_open","_close",""],function(a,c){var e="fxName"+c,g="fxSpeed"+c,j="fxSettings"+c;d[e]=h[b][e]||h[b].fxName||h.defaults[e]||h.defaults.fxName||d[e]||
d.fxName||m[e]||m.fxName||"none";var l=d[e];if(l=="none"||!f.effects||!f.effects[l]||!ua[l]&&!d[j]&&!d.fxSettings)l=d[e]="none";l=ua[l]||{};e=l.all||{};l=l[b]||{};d[j]=f.extend({},e,l,m.fxSettings||{},m[j]||{},d.fxSettings,d[j],h.defaults.fxSettings,h.defaults[j]||{},h[b].fxSettings,h[b][j]||{});d[g]=h[b][g]||h[b].fxSpeed||h.defaults[g]||h.defaults.fxSpeed||d[g]||d[j].duration||d.fxSpeed||d.fxSettings.duration||m.fxSpeed||m.fxSettings.duration||l.duration||e.duration||"normal"})})},Sa=function(a){a=
n[a].paneSelector;if("#"===a.substr(0,1))return B.find(a).eq(0);var b=B.children(a).eq(0);return b.length?b:B.children("form:first").children(a).eq(0)},bb=function(){f.each(j.allPanes.split(","),function(a,b){var c=n[b],e=l[b],d=j[b],m=d.dir,g="center"==b,i={},k,h,q;R[b]=!1;k=s[b]=Sa(b);if(!k.length)return s[b]=!1,!0;k.data("layoutCSS")||k.data("layoutCSS",va(k,"position,top,left,bottom,right,width,height,overflow,zIndex,display,backgroundColor,padding,margin,border"));k.data("layoutName",n.name).data("layoutRole",
"pane").data("layoutEdge",b).css(d.cssReq).css("zIndex",j.zIndex.pane_normal).css(c.applyDemoStyles?d.cssDemo:{}).addClass(c.paneClass+" "+c.paneClass+"-"+b).bind("mouseenter."+z,da).bind("mouseleave."+z,O);Ta(b,!1);g||(h=e.size=Q(b,c.size),d=Q(b,c.minSize)||1,q=Q(b,c.maxSize)||1E5,0<h&&(h=y(Math.min(h,q),d)));e.tagName=f.prop?k.prop("tagName"):k.attr("tagName");e.edge=b;e.noRoom=!1;e.isVisible=!0;g||(e.isClosed=!1,e.isSliding=!1,e.isResizing=!1,e.isHidden=!1);switch(b){case "north":i.top=u.insetTop;
i.left=u.insetLeft;i.right=u.insetRight;break;case "south":i.bottom=u.insetBottom;i.left=u.insetLeft;i.right=u.insetRight;break;case "west":i.left=u.insetLeft;break;case "east":i.right=u.insetRight}"horz"==m?i.height=y(1,J(b,h)):"vert"==m&&(i.width=y(1,I(b,h)));k.css(i);"horz"!=m&&S(b,!0);k.css({visibility:"visible",display:"block"});c.initClosed&&c.closable?L(b,!0,!0):(c.initHidden||c.initClosed)&&xa(b);c.showOverflowOnHover&&k.hover(V,ia)});Ua();f.each(j.borderPanes.split(","),function(a,b){s[b]&&
l[b].isVisible&&(N(b),T(b))});S("center");f.each(j.allPanes.split(","),function(a,b){var c=n[b];s[b]&&c.triggerEventsOnLoad&&l[b].isVisible&&x(b,c.onresize_end||c.onresize)});2>B.innerHeight()&&alert("UI Layout Initialization Warning\n\nThe layout-container \"CONTAINER\" has no height.\n\nTherefore the layout is 0-height and hence 'invisible'!".replace(/CONTAINER/,u.ref))},Ua=function(a){if(!a||"all"==a)a=j.borderPanes;f.each(a.split(","),function(a,c){var e=s[c];A[c]=!1;C[c]=!1;if(e){var e=n[c],
d=l[c],m=e.resizerClass,g=e.togglerClass;j[c].side.toLowerCase();var i="-"+c,k=A[c]=f("<div></div>"),h=e.closable?C[c]=f("<div></div>"):!1;!d.isVisible&&e.slidable&&k.attr("title",e.sliderTip).css("cursor",e.sliderCursor);k.attr("id","#"==e.paneSelector.substr(0,1)?e.paneSelector.substr(1)+"-resizer":"").data("layoutRole","resizer").data("layoutEdge",c).css(j.resizers.cssReq).css("zIndex",j.zIndex.resizer_normal).css(e.applyDemoStyles?j.resizers.cssDemo:{}).addClass(m+" "+m+i).appendTo(B);h&&(h.attr("id",
"#"==e.paneSelector.substr(0,1)?e.paneSelector.substr(1)+"-toggler":"").data("layoutRole","toggler").data("layoutEdge",c).css(j.togglers.cssReq).css(e.applyDemoStyles?j.togglers.cssDemo:{}).addClass(g+" "+g+i).appendTo(k).click(function(a){Z(c);a.stopPropagation()}).hover(da,O),e.togglerContent_open&&f("<span>"+e.togglerContent_open+"</span>").data("layoutRole","togglerContent").data("layoutEdge",c).addClass("content content-open").css("display","none").appendTo(h).hover(da,O),e.togglerContent_closed&&
f("<span>"+e.togglerContent_closed+"</span>").data("layoutRole","togglerContent").data("layoutEdge",c).addClass("content content-closed").css("display","none").appendTo(h).hover(da,O));cb(c);d.isVisible?ya(c):(za(c),ea(c,!0))}});fa("all")},Ta=function(a,b){var c=n[a],e=c.contentSelector,d=s[a],f;e&&(f=R[a]=c.findNestedContent?d.find(e).eq(0):d.children(e).eq(0));f&&f.length?(f.css(j.content.cssReq),c.applyDemoStyles&&(f.css(j.content.cssDemo),d.css(j.content.cssDemoPane)),l[a].content={},!1!==b&&
aa(a)):R[a]=!1},db=function(){var a;f.each("toggle,open,close,pin,toggle-slide,open-slide".split(","),function(b,c){f.each(j.borderPanes.split(","),function(b,d){f(".ui-layout-button-"+c+"-"+d).each(function(){a=f(this).data("layoutName")||f(this).attr("layoutName");(a==void 0||a==n.name)&&Ca(this,c,d)})})})},cb=function(a){var b="function"==typeof f.fn.draggable,c;if(!a||"all"==a)a=j.borderPanes;f.each(a.split(","),function(a,d){var m=n[d],g=l[d],i=j[d],k="horz"==i.dir?"top":"left",h,q;if(!b||!s[d]||
!m.resizable)return m.resizable=!1,!0;var o=A[d],p=m.resizerClass,r=p+"-drag",t=p+"-"+d+"-drag",v=p+"-dragging",w=p+"-"+d+"-dragging",y=p+"-dragging-limit",z=!1;g.isClosed||o.attr("title",m.resizerTip).css("cursor",m.resizerCursor);o.hover(Ya,Pa);o.draggable({containment:B[0],axis:"horz"==i.dir?"y":"x",delay:0,distance:1,helper:"clone",opacity:m.resizerDragOpacity,addClasses:!1,zIndex:j.zIndex.resizer_drag,start:function(){m=n[d];g=l[d];q=m.resizeWhileDragging;if(!1===x(d,m.ondrag_start))return!1;
j.isLayoutBusy=!0;g.isResizing=!0;D.clear(d+"_closeSlider");N(d);h=g.resizerPosition;o.addClass(r+" "+t);z=!1;c=f(!0===m.maskIframesOnResize?"iframe":m.maskIframesOnResize).filter(":visible");var a,b=0;c.each(function(){a="ui-layout-mask-"+ ++b;f(this).data("layoutMaskID",a);f('<div id="'+a+'" class="ui-layout-mask ui-layout-mask-'+d+'"/>').css({background:"#fff",opacity:"0.001",zIndex:j.zIndex.iframe_mask,position:"absolute",width:this.offsetWidth+"px",height:this.offsetHeight+"px"}).css(f(this).position()).appendTo(this.parentNode)});
f("body").disableSelection()},drag:function(a,b){z||(b.helper.addClass(v+" "+w).children().css("visibility","hidden"),z=!0,g.isSliding&&s[d].css("zIndex",j.zIndex.pane_sliding));var c=0;b.position[k]<h.min?(b.position[k]=h.min,c=-1):b.position[k]>h.max&&(b.position[k]=h.max,c=1);c?(b.helper.addClass(y),window.defaultStatus="Panel has reached its "+(0<c&&d.match(/north|west/)||0>c&&d.match(/south|east/)?"maximum":"minimum")+" size"):(b.helper.removeClass(y),window.defaultStatus="");q&&C(a,b,d)},stop:function(a,
b){f("body").enableSelection();window.defaultStatus="";o.removeClass(r+" "+t+" "+y);g.isResizing=!1;j.isLayoutBusy=!1;C(a,b,d,!0)}});var C=function(a,b,d,e){var a=b.position,b=j[d],g;switch(d){case "north":g=a.top;break;case "west":g=a.left;break;case "south":g=u.offsetHeight-a.top-m.spacing_open;break;case "east":g=u.offsetWidth-a.left-m.spacing_open}if(e){if(f("div.ui-layout-mask").each(function(){this.parentNode.removeChild(this)}),!1===x(d,m.ondrag_end||m.ondrag))return!1}else c.each(function(){f("#"+
f(this).data("layoutMaskID")).css(f(this).position()).css({width:this.offsetWidth+"px",height:this.offsetHeight+"px"})});Aa(d,g-u["inset"+b.side])}})},xa=function(a,b){var c=n[a],e=l[a],d=s[a],f=A[a];if(d&&!e.isHidden&&!(l.initialized&&!1===x(a,c.onhide_start)))if(e.isSliding=!1,f&&f.hide(),!l.initialized||e.isClosed){if(e.isClosed=!0,e.isHidden=!0,e.isVisible=!1,d.hide(),S("horz"==j[a].dir?"all":"center"),l.initialized||c.triggerEventsOnLoad)x(a,c.onhide_end||c.onhide)}else e.isHiding=!0,L(a,!1,
b)},ma=function(a,b,c,e){var d=n[a],f=l[a];s[a]&&f.isHidden&&!1!==x(a,d.onshow_start)&&(f.isSliding=!1,f.isShowing=!0,!1===b?L(a,!0):P(a,!1,c,e))},Z=function(a,b){H(a)||(a.stopImmediatePropagation(),a=f(this).data("layoutEdge"));var c=l[H(a)?f.trim(a):void 0==a||null==a?"":a];c.isHidden?ma(a):c.isClosed?P(a,!!b):L(a)},eb=function(a){var b=l[a];s[a].hide();b.isClosed=!0;b.isVisible=!1},L=function(a,b,c,e){function d(){if(i.isClosed){ea(a,!0);var b=j.altSide[a];l[b].noRoom&&(N(b),T(b));if(!e&&(l.initialized||
g.triggerEventsOnLoad))k||x(a,g.onclose_end||g.onclose),k&&x(a,g.onshow_end||g.onshow),h&&x(a,g.onhide_end||g.onhide)}La(a)}if(l.initialized){var f=s[a],g=n[a],i=l[a],c=!c&&!i.isClosed&&"none"!=g.fxName_close,k=i.isShowing,h=i.isHiding;delete i.isShowing;delete i.isHiding;if(f&&g.closable&&(b||!i.isClosed||k))if(j.isLayoutBusy)Ka("close",a,b);else if(k||!1!==x(a,g.onclose_start))(j[a].isMoving=!0,j.isLayoutBusy=!0,i.isClosed=!0,i.isVisible=!1,h?i.isHidden=!0:k&&(i.isHidden=!1),i.isSliding?ga(a,!1):
S("horz"==j[a].dir?"all":"center",!1),za(a),c)?(na(a,!0),f.hide(g.fxName_close,g.fxSettings_close,g.fxSpeed_close,function(){na(a,false);d()})):(f.hide(),d())}else eb(a)},za=function(a){var b=A[a],c=C[a],e=n[a],d=j[a].side.toLowerCase(),m=e.resizerClass,g=e.togglerClass,i="-"+a;b.css(d,u["inset"+j[a].side]).removeClass(m+"-open "+m+i+"-open").removeClass(m+"-sliding "+m+i+"-sliding").addClass(m+"-closed "+m+i+"-closed").unbind("dblclick."+z);e.resizable&&"function"==typeof f.fn.draggable&&b.draggable("disable").removeClass("ui-state-disabled").css("cursor",
"default").attr("title","");c&&(c.removeClass(g+"-open "+g+i+"-open").addClass(g+"-closed "+g+i+"-closed").attr("title",e.togglerTip_closed),c.children(".content-open").hide(),c.children(".content-closed").css("display","block"));ra(a,!1);l.initialized&&fa("all")},P=function(a,b,c,e){function d(){i.isVisible&&(Oa(a),i.isSliding||S("vert"==j[a].dir?"center":"all",!1),ya(a));La(a)}var f=s[a],g=n[a],i=l[a],c=!c&&i.isClosed&&"none"!=g.fxName_open,k=i.isShowing;delete i.isShowing;if(f&&(g.resizable||g.closable)&&
(!i.isVisible||i.isSliding))i.isHidden&&!k?ma(a,!0):j.isLayoutBusy?Ka("open",a,b):!1!==x(a,g.onopen_start)&&((N(a,b),i.minSize>i.maxSize)?(ra(a,!1),!e&&g.noRoomToOpenTip&&alert(g.noRoomToOpenTip)):(j[a].isMoving=!0,j.isLayoutBusy=!0,b?ga(a,!0):i.isSliding?ga(a,!1):g.slidable&&ea(a,!1),i.noRoom=!1,T(a),i.isVisible=!0,i.isClosed=!1,k&&(i.isHidden=!1),c)?(na(a,!0),f.show(g.fxName_open,g.fxSettings_open,g.fxSpeed_open,function(){na(a,false);d()})):(f.show(),d()))},ya=function(a,b){var c=s[a],e=A[a],d=
C[a],m=n[a],g=l[a],i=j[a].side.toLowerCase(),k=m.resizerClass,h=m.togglerClass,q="-"+a;e.css(i,u["inset"+j[a].side]+M(a)).removeClass(k+"-closed "+k+q+"-closed").addClass(k+"-open "+k+q+"-open");g.isSliding?e.addClass(k+"-sliding "+k+q+"-sliding"):e.removeClass(k+"-sliding "+k+q+"-sliding");m.resizerDblClickToggle&&e.bind("dblclick",Z);O(0,e);m.resizable&&"function"==typeof f.fn.draggable?e.draggable("enable").css("cursor",m.resizerCursor).attr("title",m.resizerTip):g.isSliding||e.css("cursor","default");
d&&(d.removeClass(h+"-closed "+h+q+"-closed").addClass(h+"-open "+h+q+"-open").attr("title",m.togglerTip_open),O(0,d),d.children(".content-closed").hide(),d.children(".content-open").css("display","block"));ra(a,!g.isSliding);f.extend(g,X(c));l.initialized&&(fa("all"),aa(a,!0));if(!b&&(l.initialized||m.triggerEventsOnLoad)&&c.is(":visible"))x(a,m.onopen_end||m.onopen),g.isShowing&&x(a,m.onshow_end||m.onshow),l.initialized&&(x(a,m.onresize_end||m.onresize),ha(a))},Va=function(a){var b=typeof a,c="string"==
b?a:f(this).data("layoutEdge");"object"==b&&a.stopImmediatePropagation();l[c].isClosed?P(c,!0):ga(c,!0)},Ba=function(a){function b(){e.isClosed?ga(c,!1):L(c)}var c=(H(a)?s[a]:f(this)).data("layoutEdge"),a=n[c],e=l[c];!e.isClosed&&!e.isResizing&&("click"==a.slideTrigger_close?b():(!a.preventQuickSlideClose||!j.isLayoutBusy)&&D.set(c+"_closeSlider",b,300))},na=function(a,b){var c=s[a];if(b)c.css({zIndex:j.zIndex.pane_animate}),"south"==a?c.css({top:u.insetTop+u.innerHeight-c.outerHeight()}):"east"==
a&&c.css({left:u.insetLeft+u.innerWidth-c.outerWidth()});else{c.css({zIndex:l[a].isSliding?j.zIndex.pane_sliding:j.zIndex.pane_normal});"south"==a?c.css({top:"auto"}):"east"==a&&c.css({left:"auto"});var e=n[a];l.browser.msie&&e.fxOpacityFix&&"slide"!=e.fxName_open&&c.css("filter")&&1==c.css("opacity")&&c[0].style.removeAttribute("filter")}},ea=function(a,b){var c=n[a],e=A[a],d=c.slideTrigger_open;e&&c.slidable&&(d.match(/mouseover/)?d=c.slideTrigger_open="mouseenter":d.match(/click|dblclick|mouseenter/)||
(d=c.slideTrigger_open="click"),e[b?"bind":"unbind"](d+"."+z,Va).css("cursor",b?c.sliderCursor:"default").attr("title",b?c.sliderTip:""))},ga=function(a,b){function c(b){D.clear(a+"_closeSlider");b.stopPropagation()}var e=n[a],d=j.zIndex,f=e.slideTrigger_close,g=b?"bind":"unbind",i=s[a],k=A[a];l[a].isSliding=b;D.clear(a+"_closeSlider");b&&ea(a,!1);i.css("zIndex",b?d.pane_sliding:d.pane_normal);k.css("zIndex",b?d.pane_sliding:d.resizer_normal);f.match(/click|mouseleave/)||(f=e.slideTrigger_close="mouseleave");
k[g](f,Ba);"mouseleave"==f&&(i[g]("mouseleave."+z,Ba),k[g]("mouseenter."+z,c),i[g]("mouseenter."+z,c));b?"click"==f&&!e.resizable&&(k.css("cursor",b?e.sliderCursor:"default"),k.attr("title",b?e.togglerTip_open:"")):D.clear(a+"_closeSlider")},T=function(a,b,c,e){var b=n[a],d=l[a],f=j[a],g=s[a],i=A[a],k="vert"==f.dir,h=!1;if("center"==a||k&&d.noVerticalRoom)(h=d.minHeight<=d.maxHeight&&(k||d.minWidth<=d.maxWidth))&&d.noRoom?(g.show(),i&&i.show(),d.isVisible=!0,d.noRoom=!1,k&&(d.noVerticalRoom=!1),Oa(a)):
!h&&!d.noRoom&&(g.hide(),i&&i.hide(),d.isVisible=!1,d.noRoom=!0);if("center"!=a)if(d.minSize<=d.maxSize){if(d.size>d.maxSize?ba(a,d.maxSize,c,e):d.size<d.minSize?ba(a,d.minSize,c,e):i&&g.is(":visible")&&(c=f.side.toLowerCase(),e=d.size+u["inset"+f.side],W(i,c)!=e&&i.css(c,e)),d.noRoom)d.wasOpen&&b.closable?b.autoReopen?P(a,!1,!0,!0):d.noRoom=!1:ma(a,d.wasOpen,!0,!0)}else d.noRoom||(d.noRoom=!0,d.wasOpen=!d.isClosed&&!d.isSliding,b.closable?L(a,!0,!0):xa(a,!0))},Aa=function(a,b,c){var e=n[a],d=e.resizeWhileDragging&&
!j.isLayoutBusy;e.autoResize=!1;ba(a,b,c,d)},ba=function(a,b,c,e){var d=n[a],h=l[a],g=s[a],i=A[a],k=j[a].side.toLowerCase(),o="inset"+j[a].side,q=j.isLayoutBusy&&!d.triggerEventsWhileDragging,p;N(a);p=h.size;b=Q(a,b);b=y(b,Q(a,d.minSize));b=Math.min(b,h.maxSize);if(b<h.minSize)T(a,!1,c);else if(e||b!=p)if(!c&&l.initialized&&h.isVisible&&x(a,d.onresize_start),g.css(j[a].sizeType.toLowerCase(),y(1,"horz"==j[a].dir?J(a,b):I(a,b))),h.size=b,f.extend(h,X(g)),i&&g.is(":visible")&&i.css(k,b+u[o]),aa(a),
!c&&!q&&l.initialized&&h.isVisible&&(x(a,d.onresize_end||d.onresize),ha(a)),c||(h.isSliding||S("horz"==j[a].dir?"all":"center",q,e),fa("all")),a=j.altSide[a],b<p&&l[a].noRoom)N(a),T(a,!1,c)},S=function(a,b,c){if(!a||"all"==a)a="east,west,center";f.each(a.split(","),function(a,d){if(s[d]){var h=n[d],g=l[d],i=s[d],k=!0,j={},k={top:M("north",!0),bottom:M("south",!0),left:M("west",!0),right:M("east",!0),width:0,height:0};k.width=u.innerWidth-k.left-k.right;k.height=u.innerHeight-k.bottom-k.top;k.top+=
u.insetTop;k.bottom+=u.insetBottom;k.left+=u.insetLeft;k.right+=u.insetRight;f.extend(g,X(i));if("center"==d){if(!c&&g.isVisible&&k.width==g.outerWidth&&k.height==g.outerHeight)return!0;f.extend(g,ka(d),{maxWidth:k.width,maxHeight:k.height});j=k;j.width=I(d,k.width);j.height=J(d,k.height);k=0<j.width&&0<j.height;if(!k&&!l.initialized&&0<h.minWidth){var q=h.minWidth-g.outerWidth,o=n.east.minSize||0,p=n.west.minSize||0,r=l.east.size,t=l.west.size,v=r,w=t;0<q&&l.east.isVisible&&r>o&&(v=y(r-o,r-q),q-=
r-v);0<q&&l.west.isVisible&&t>p&&(w=y(t-p,t-q),q-=t-w);if(0==q){r!=o&&ba("east",v,!0);t!=p&&ba("west",w,!0);S("center",b,c);return}}}else{f.extend(g,X(i),ka(d));if(!c&&!g.noVerticalRoom&&k.height==g.outerHeight)return!0;j.top=k.top;j.bottom=k.bottom;j.height=J(d,k.height);g.maxHeight=y(0,j.height);k=0<g.maxHeight;k||(g.noVerticalRoom=!0)}k?(!b&&l.initialized&&x(d,h.onresize_start),i.css(j),f.extend(g,X(i)),g.noRoom&&T(d),l.initialized&&aa(d)):!g.noRoom&&g.isVisible&&T(d);"center"==d&&(i=l.browser,
i=i.isIE6||i.msie&&!i.boxModel,s.north&&(i||"IFRAME"==l.north.tagName)&&s.north.css("width",I(s.north,u.innerWidth)),s.south&&(i||"IFRAME"==l.south.tagName)&&s.south.css("width",I(s.south,u.innerWidth)));!b&&l.initialized&&g.isVisible&&(x(d,h.onresize_end||h.onresize),ha(d))}})},la=function(){f.extend(l.container,X(B));if(u.outerHeight){if(!1===x(null,n.onresizeall_start))return!1;var a,b,c;f.each(["south","north","east","west"],function(a,d){s[d]&&(c=l[d],b=n[d],b.autoResize&&c.size!=b.size?ba(d,
b.size,!0,!0):(N(d),T(d,!1,!0,!0)))});S("all",!0,!0);fa("all");b=n;f.each(j.allPanes.split(","),function(c,d){if(a=s[d])l[d].isVisible&&x(d,b[d].onresize_end||b[d].onresize),ha(d)});x(null,b.onresizeall_end||b.onresizeall)}},ha=function(a){var b=s[a],c=R[a];n[a].resizeNestedLayout&&(b.data("layoutContainer")?b.layout().resizeAll():c&&c.data("layoutContainer")&&c.layout().resizeAll())},aa=function(a,b){if(!a||"all"==a)a=j.allPanes;f.each(a.split(","),function(a,e){function d(a){return y(o.css.paddingBottom,
parseInt(a.css("marginBottom"),10)||0)}function f(){var a=n[e].contentIgnoreSelector,a=i.nextAll().not(a||":lt(0)"),b=a.filter(":visible"),c=b.filter(":last");q={top:i[0].offsetTop,height:i.outerHeight(),numFooters:a.length,hiddenFooters:a.length-b.length,spaceBelow:0};q.spaceAbove=q.top;q.bottom=q.top+q.height;q.spaceBelow=c.length?c[0].offsetTop+c.outerHeight()-q.bottom+d(c):d(i)}var g=s[e],i=R[e],h=n[e],o=l[e],q=o.content;if(!g||!i||!g.is(":visible"))return!0;if(!1!==x(null,h.onsizecontent_start)){if(!j.isLayoutBusy||
void 0==q.top||b||h.resizeContentWhileDragging)f(),0<q.hiddenFooters&&"hidden"==g.css("overflow")&&(g.css("overflow","visible"),f(),g.css("overflow","hidden"));g=o.innerHeight-(q.spaceAbove-o.css.paddingTop)-(q.spaceBelow-o.css.paddingBottom);if(!i.is(":visible")||q.height!=g)Xa(i,g,!0),q.height=g;l.initialized&&(x(e,h.onsizecontent_end||h.onsizecontent),ha(e))}})},fa=function(a){if(!a||"all"==a)a=j.borderPanes;f.each(a.split(","),function(a,c){var e=n[c],d=l[c],h=s[c],g=A[c],i=C[c],k;if(h&&g){var o=
j[c].dir,q=d.isClosed?"_closed":"_open",p=e["spacing"+q],r=e["togglerAlign"+q],q=e["togglerLength"+q],t;if(0==p)g.hide();else{!d.noRoom&&!d.isHidden&&g.show();"horz"==o?(t=h.outerWidth(),d.resizerLength=t,g.css({width:y(1,I(g,t)),height:y(0,J(g,p)),left:W(h,"left")})):(t=h.outerHeight(),d.resizerLength=t,g.css({height:y(1,J(g,t)),width:y(0,I(g,p)),top:u.insetTop+M("north",!0)}));O(e,g);if(i){if(0==q||d.isSliding&&e.hideTogglerOnSlide){i.hide();return}i.show();if(!(0<q)||"100%"==q||q>t)q=t,r=0;else if(H(r))switch(r){case "top":case "left":r=
0;break;case "bottom":case "right":r=t-q;break;default:r=Math.floor((t-q)/2)}else d=parseInt(r,10),r=0<=r?d:t-q+d;if("horz"==o){var v=I(i,q);i.css({width:y(0,v),height:y(1,J(i,p)),left:r,top:0});i.children(".content").each(function(){k=f(this);k.css("marginLeft",Math.floor((v-k.outerWidth())/2))})}else{var w=J(i,q);i.css({height:y(0,w),width:y(1,I(i,p)),top:r,left:0});i.children(".content").each(function(){k=f(this);k.css("marginTop",Math.floor((w-k.outerHeight())/2))})}O(0,i)}!l.initialized&&e.initHidden&&
(g.hide(),i&&i.hide())}}})},B=f(this).eq(0);if(!B.length)return null;if(B.data("layoutContainer"))return f.extend({},window[B.data("layoutContainer")]);var s={},R={},A={},C={},u=l.container,z=l.id;(function(){ab();var a=n;if(!1===x(null,a.onload))return!1;if(!Sa("center").length)return alert("UI Layout Initialization Error\n\nThe center-pane element does not exist.\n\nThe center-pane is a required element."),null;a.useStateCookie&&a.cookie.autoLoad&&Ia();l.browser={mozilla:f.browser.mozilla,webkit:f.browser.webkit||
f.browser.safari,msie:f.browser.msie,isIE6:f.browser.msie&&6==f.browser.version,boxModel:f.support.boxModel};var b=B,c=u.tagName=f.prop?b.prop("tagName"):b.attr("tagName"),e="BODY"==c,d={};u.selector=b.selector.split(".slice")[0];u.ref=c+"/"+u.selector;b.data("layoutContainer",z).data("layoutName",n.name);b.data("layoutCSS")||(e?(d=f.extend(va(b,"position,margin,padding,border"),{height:b.css("height"),overflow:b.css("overflow"),overflowX:b.css("overflowX"),overflowY:b.css("overflowY")}),c=f("html"),
c.data("layoutCSS",{height:"auto",overflow:c.css("overflow"),overflowX:c.css("overflowX"),overflowY:c.css("overflowY")})):d=va(b,"position,margin,padding,border,top,bottom,left,right,width,height,overflow,overflowX,overflowY"),b.data("layoutCSS",d));try{if(e)f("html").css({height:"100%",overflow:"hidden",overflowX:"hidden",overflowY:"hidden"}),f("body").css({position:"relative",height:"100%",overflow:"hidden",overflowX:"hidden",overflowY:"hidden",margin:0,padding:0,border:"none"});else{var d={overflow:"hidden"},
h=b.css("position");b.css("height");if(!b.data("layoutRole")&&(!h||!h.match(/fixed|absolute|relative/)))d.position="relative";b.css(d);b.is(":visible")&&2>b.innerHeight()&&alert("UI Layout Initialization Warning\n\nThe layout-container \"CONTAINER\" has no height.\n\nTherefore the layout is 0-height and hence 'invisible'!".replace(/CONTAINER/,u.ref))}}catch(g){}f.extend(l.container,X(b));bb();aa();a.scrollToBookmarkOnLoad&&(b=self.location,b.hash&&b.replace(b.hash));a.autoBindCustomButtons&&db();
$a();a.resizeWithWindow&&!B.data("layoutRole")&&f(window).bind("resize."+z,Za);f(window).bind("unload."+z,Ra);l.initialized=!0})();var Ma={options:n,state:l,container:B,panes:s,contents:R,resizers:A,togglers:C,toggle:Z,hide:xa,show:ma,open:P,close:L,slideOpen:Va,slideClose:Ba,slideToggle:function(a){Z(a,!0)},initContent:Ta,sizeContent:aa,sizePane:Aa,swapPanes:function(a,b){function c(a){var b=s[a],c=R[a];return!b?!1:{pane:a,P:b?b[0]:!1,C:c?c[0]:!1,state:f.extend({},l[a]),options:f.extend({},n[a])}}
function e(a,b){if(a){var c=a.P,d=a.C,e=a.pane,h=j[b],m=h.side.toLowerCase(),o="inset"+h.side,p=f.extend({},l[b]),r=n[b],t={resizerCursor:r.resizerCursor};f.each(["fxName","fxSpeed","fxSettings"],function(a,b){t[b]=r[b];t[b+"_open"]=r[b+"_open"];t[b+"_close"]=r[b+"_close"]});s[b]=f(c).data("layoutEdge",b).css(j.hidden).css(h.cssReq);R[b]=d?f(d):!1;n[b]=f.extend({},a.options,t);l[b]=f.extend({},a.state);c.className=c.className.replace(RegExp(r.paneClass+"-"+e,"g"),r.paneClass+"-"+b);Ua(b);h.dir!=j[e].dir?
(c=g[b]||0,N(b),c=y(c,l[b].minSize),Aa(b,c,!0)):A[b].css(m,u[o]+(l[b].isVisible?M(b):0));a.state.isVisible&&!p.isVisible?ya(b,!0):(za(b),ea(b,!0));a=null}}l[a].edge=b;l[b].edge=a;var d=!1;!1===x(a,n[a].onswap_start)&&(d=!0);!d&&!1===x(b,n[b].onswap_start)&&(d=!0);if(d)l[a].edge=a,l[b].edge=b;else{var d=c(a),h=c(b),g={};g[a]=d?d.state.size:0;g[b]=h?h.state.size:0;s[a]=!1;s[b]=!1;l[a]={};l[b]={};C[a]&&C[a].remove();C[b]&&C[b].remove();A[a]&&A[a].remove();A[b]&&A[b].remove();A[a]=A[b]=C[a]=C[b]=!1;e(d,
b);e(h,a);d=h=g=null;s[a]&&s[a].css(j.visible);s[b]&&s[b].css(j.visible);la();x(a,n[a].onswap_end||n[a].onswap);x(b,n[b].onswap_end||n[b].onswap)}},resizeAll:la,destroy:function(){f(window).unbind("."+z);f(document).unbind("."+z);window[z]=null;var a="BODY"==u.tagName,b,c,e,d;f.each(j.allPanes.split(","),function(a,g){b=s[g];if(!b)return!0;"center"!=g&&(C[g]&&C[g].remove(),A[g].remove());c=n[g].paneClass;e=c+"-"+g;d=[c,c+"-open",c+"-closed",c+"-sliding",e,e+"-open",e+"-closed",e+"-sliding"];f.merge(d,
wa(b,!0));b.removeClass(d.join(" ")).removeData("layoutRole").removeData("layoutEdge").unbind("."+z).unbind("mouseenter").unbind("mouseleave");b.data("layoutContainer")||b.css(b.data("layoutCSS"))});B.removeData("layoutContainer");B.data("layoutEdge")||B.css(B.data("layoutCSS"));a&&f("html").css(f("html").data("layoutCSS"));Ra();(a=n.name)&&window[a]&&(window[a]=null)},setSizeLimits:N,bindButton:Ca,addToggleBtn:oa,addOpenBtn:pa,addCloseBtn:Da,addPinBtn:Ea,allowOverflow:V,resetOverflow:ia,encodeJSON:Ha,
decodeJSON:Ga,getState:ta,getCookie:Fa,saveCookie:sa,deleteCookie:function(){sa("",{expires:-1})},loadCookie:Ia,loadState:Ja,cssWidth:I,cssHeight:J};return window[z]=Ma}})(jQuery);
var layoutState={options:{layoutName:"mywebsql",keys:"north__size,south__size,east__size,west__size,north__isClosed,south__isClosed,east__isClosed,west__isClosed,north__isHidden,south__isHidden,east__isHidden,west__isHidden",domain:"",path:"",expires:"60",secure:!1},data:{},clear:function(f){this.save(f,"layout",{expires:-1})},save:function(f,t,h){var h=jQuery.extend({},this.options,h||{}),o=window[f||h.layoutName];t||(t=h.keys);"string"==typeof t&&(t=t.split(","));if(!o||!o.state||!t.length)return!1;
var p="number"==typeof h.expires,r=new Date,E="",G=!1;if(p||h.expires.toUTCString)p?0>=h.expires?(r.setYear(1970),G=!0):r.setTime(r.getTime()+864E5*h.expires):r=h.expires,E+=";expires="+r.toUTCString();h.path&&(E+=";path="+h.path);h.domain&&(E+=";domain="+h.domain);h.secure&&(E+=";secure");if(G)this.data={},$.cookies.set(f||h.layoutName,E,{path:EXTERNAL_PATH,hoursToLive:COOKIE_LIFETIME});else{for(var o=o.state,p={},r={isClosed:"initClosed",isHidden:"initHidden"},G=0<t[0].indexOf("__")?"__":".",v,
w,F,K=0;K<t.length;K++)v=t[K].split(G),w=v[0],v=v[1],0>"north,south,east,west,center".indexOf(w)||(F="isClosed"==v?o[w][v]||o[w].isSliding:o[w][v],void 0!=F&&("."==G?(p[w]||(p[w]={}),p[w][r[v]?r[v]:v]=F):p[w+G+(r[v]?r[v]:v)]=F));this.data=p;$.cookies.set(f||h.layoutName,encodeURIComponent(JSON.stringify(this.data))+E,{path:EXTERNAL_PATH,hoursToLive:COOKIE_LIFETIME})}return this.data},load:function(f){f||(f=this.options.layoutName);if(!f)return{};var t={};(ck=$.cookies.get(f))&&(t=JSON.parse(decodeURIComponent(ck)));
return this.data=t}};
